## Topic: 1. Introduction of Numpy Array

### OUTCOMES

- 1. Introduction and Create ndarray

- 2. ndarray and it's attributes

- 3. Changing Data type.

- 4. Numpy array vs. Python sequence

### 1. Introduction and Create ndarray

- Introduction:
    - Numpy refers numerical python.
    - it's a library that mainly focus on the numpy array (ndarray).


- Definiton of Array:
    - An Array is a linear static data structure that store a collection of elements, typically of the same data type in a contiguous block of memory.

    - here,
        - linear => in memory data to data relation/connection
        - static => memory size is fixed.
        - same data tyep => homogenous data

- Type of array
    - 1. 0-d array (scalar).
    - 2. 1-d arrary (vector)
    - 3. 2-d arrary (Matrics)
    - 4. 3-d array (Tensor)
    ...................
    - nd array



- Syntax of ndarra for create:
    - arr_name = np.array(sequenc, dtype=none)

    - here,
        - arr_name like a variable
        - np.array() is a function provided by the NumPy library that is used to create an ndarray.


In [3]:
# Example_01: create a ndarry
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))
# print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# Example: 0-d (scalar) array create
# scalar -> A constant or single value that hold a piece of data.

arr0 = np.array(12)

print(arr0)
print(type(arr0))

# print(arr.dtype)
# print(arr0.ndim)


12
<class 'numpy.ndarray'>


In [5]:
# Example: 1-d array or vector create

# Vector (1-d) : A linear array that holds elements in single row or column.
# only one subscript []

arr1 = np.array([1,2,3,4,5,6])

print(arr1)

# print(arr1.ndim)


[1 2 3 4 5 6]


In [ ]:
# Example : 2-d or Matrix Create

# Matrix(2-d): A grid-like structure that holds elements in rows and columns
#  -> A Rectangular collection of elements 
# Represent: Two subsript [[]]


arr2 = np.array(
    [[1,2,3],
    [4,5,6],      # here, rows = 3 and columns = 3
    [7,8,9]]
 )

print(arr2)

# print(arr2.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Example: 3-d or tensor 
# Tensor(3-d): A 3-d array is collection of 2-d arrays stacked along a third dimension.


arr3 = np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],

    [[1,2,3],
    [4,5,6],
    [7,8,9]]


])

print(arr3)
# print(arr3.ndim)
# print(arr3.shape)



# syntax of 3-d array:
# first -> no of depth (2)
# 2nd   -> no of rows of each depth (3)
# 3rd   -> no of columns of each depth (3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(2, 3, 3)


### 2. ndarray and it's attribute

In [14]:
# 1. arr.ndim : return the number of dimension of ndarray

arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)  # 1-d array 


# apply for 2-d 

arr2 = np.array([[10, 20, 30], [40, 50, 60, ], [70, 80, 90]])

print("Array_2 : \n", arr2)
print("Dimension: ", arr2.ndim)


# apply for 3-d array

arr3 = np.array([
    [[1,2,3]],
    [[4,5,6]]
])

print(arr3)

print(arr3.ndim)

[1 2 3 4]
1
Array_2 : 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension:  2
[[[1 2 3]]

 [[4 5 6]]]
3


In [ ]:
# 2. arr.shape : shape of the ndarray

# Example: 1-d

print(arr1.shape)  # for 1-d : Return the number of elements

# Example: 2-d

print(arr2.shape)  # for 2-d: Return the no of rows and columns

# Example: 3-d

print(arr3.shape) # for 3-d: first depth then each depth no of rows and columns


(4,)
(3, 3)
(2, 1, 3)


In [ ]:
# 3. arr.size : Return totla numbers of element in ndarray

print("1-d: ", arr1.size) # 4 -> total no of elements in 1-d array
print("2-d: ", arr2.size) # 9 -> total no of elements in 2-d array
print("3-d: ", arr3.size) # 6 -> total no of elements in 3-d array

1-d:  4
2-d:  9
3-d:  6


In [ ]:
# 4. arr.dtype : Return the type inside the ndarray elements

arr_f = np.array([10.5,20.5, 30.2, 60.5])

print(arr_f.dtype)

# if combine 

arr_mix = np.array([10, 20.5, 55, 80.56]) # follow upcasting method

print(arr_mix.dtype) # float is the bigger than integer

float64
float64


In [ ]:
# 5. arr.itemsize : Return the byte size of each items occupied in memory

print(arr_mix.itemsize)  # 8 byte

arr_m = np.array([10.5,20.5, "Hello"])

print(arr_m.itemsize) 
print(arr_m) 

8
128
['10.5' '20.5' 'Hello']


In [ ]:
# 6. arr.nbytes: Return the total bytes consumed by the ndarray

print("arr1: ", arr1.nbytes)
print("arr2: ", arr2.nbytes)
print("arr3: ", arr3.nbytes)

print("arr_m: ", arr_m.nbytes)


# nbytes: arr.size * arr.itemsize

print(arr1.size * arr1.itemsize)

arr1:  32
arr2:  72
arr3:  48
arr_m:  384
32


### 3. Changing Data type.

- Why need?
 
 - Different data types consume different amounts of memory

    - int8  uses 1 byte per element
    - int16 uses 2 bytes per element
    - int32 uses 4 bytes per element.
    - int64 uses 8 bytes per element.
    - float64 uses 8 bytes, while float32 uses 4 bytes.

- To optimise memory usage, we need to change the data types.

- Two way to change Data type
    - 1. np.array(sequence, dtype = np.int8) then input a sequece type of data is change.

    - 2. arr.astype(np.int32) => using astype() function

In [ ]:
# Example - 1: np.array() : To convert default nature(int64) to float32

lst = [10, 20, 30, 40]

lst_float = np.array(lst, dtype= np.float32)  # upcasting to int64 to float32

print(lst_float)

[10. 20. 30. 40.]


In [ ]:
# Example - 1: np.array(sequence, dtype = np.int8) 

arr = np.array([1,2,3,4,5,6])  # default data type int64

print(arr)

print("Each item consume memory: ", arr.itemsize)
print("Total Memory Occupied: ", arr.nbytes)

[1 2 3 4 5 6]
Each item consume memory:  8
Total Memory Occupied:  48


In [ ]:
# Example - 1: np.array(sequence, dtype = np.int8)

# upcasting int64 to int32
arr = np.array([1,2,3,4,5,6],dtype = np.int32)

print(arr)

print("Each item consume memory: ", arr.itemsize)
print("Total Memory Occupied: ", arr.nbytes)


# This is the difference the above same program total memory consume memory 48 bytes
# when we convert into int32 the total memory consume 24 bytes(which is half)

[1 2 3 4 5 6]
Each item consume memory:  4
Total Memory Occupied:  24


In [ ]:
# Example - 2: arr.astype(np.float32)

arr64 = np.array([10.2, 11.2,  12.5, 13.5, 14.5])

print(arr64)

print("Each item consume memory: ", arr64.itemsize)
print("Total Memory Occupied: ", arr64.nbytes)



[10.2 11.2 12.5 13.5 14.5]
Each item consume memory:  8
Total Memory Occupied:  40


In [ ]:
# Example - 2: arr.astype(np.float32)

arr64 = np.array([10.2, 11.2,  12.5, 13.5, 14.5],dtype = np.float32)

print(arr64)

print("Each item consume memory: ", arr64.itemsize)
print("Total Memory Occupied: ", arr64.nbytes)

[10.2 11.2 12.5 13.5 14.5]
Each item consume memory:  4
Total Memory Occupied:  20


In [66]:
# Example - 2: arr.astype(np.int8)

arr = np.array([1,2, 3,4,5,6])

print(arr)
print("Total Memoryt Consume: ", arr.nbytes)

arr = arr.astype(np.int8)
print(arr)
print("After convert to int8 Total Memoryt Consume: ", arr.nbytes)

[1 2 3 4 5 6]
Total Memoryt Consume:  48
[1 2 3 4 5 6]
After convert to int8 Total Memoryt Consume:  6


In [81]:
# Upcasting careful -> the range values that contain int8 (-127 to 128)
ar = np.array([1,200, 300,4,-129,6])

# if we try to convert int8 then it's generated

ar = ar.astype(np.int8) 

print(ar)
print("After convert to int8 Total Memoryt Consume: ", ar.nbytes)
print(ar.dtype)



[  1 -56  44   4 127   6]
After convert to int8 Total Memoryt Consume:  6
int8


In [ ]:
# upcasting to string

lst = [1,2,3,4, "hello", 10.23]

arr_lst = np.array([lst], dtype=np.float32) # generate ValueError



ValueError: could not convert string to float: 'hello'

In [80]:
# upcasting string to float

lst = [1,2,3,4, "2", 10.23]
arr_lst = np.array([lst], dtype=np.float32) 

print(arr_lst)
print(arr_lst.dtype)


[[ 1.    2.    3.    4.    2.   10.23]]
float32


In [79]:
# upcasting default data to string

arr_str = np.array([1,2,3,'h', 10.50])
print(arr_str)
print(arr_str.dtype)

['1' '2' '3' 'h' '10.5']
<U32


### 4. Numpy array vs Python sequence

- python sequence (list):
    - Heterogeous (not same data type)
    - slower to large datasets (because data to data relation is non-linear)
    - Perform basic indexing and slicing


- ndarray (Numpy Array):
    - Homogeneous (same data type of all elements)
    - Faster compare to list (Because data to relation is linear)
    - support advance indexing and slicing 

In [ ]:
# Check to list how many to access elements
import time 

lst = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

current_time = time.time()
print(current_time)

# access list elements
for i in lst:
    print(i)
now_time = time.time()

print("Required time to access list element: ",now_time-current_time)

1760873581.8352532
10
20
30
40
50
60
70
80
90
100
Required time to access list element:  0.0004718303680419922


In [ ]:
# Check to ndarray how many to access elements

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

curr_time = time.time()

# access element
print(arr)

n_time = time.time()
print("Required time to access ndarray element: ",n_time-curr_time)





[ 10  20  30  40  50  60  70  80  90 100]
Required time to access ndarray element:  0.0003223419189453125
