### 2. ndarray Creation form existing data type (list, dic, etc)

### OUCOMES

- 1. List to ndarray

- 2. tuple to ndarray

- 3. set to ndarry

- 4. dic to ndarray


### 1. List to ndarray

In [2]:
import numpy as np

In [ ]:
# Example: list to ndarray Create

lst = [10, 20, 30, 40, 50.44]

arr = np.array(lst, dtype = np.int32)

print(arr)
print("Type       : ", type(arr))
print("Shape      : ", arr.shape)
print("Dimension  : ", arr.ndim)
print("Element type: ", arr.dtype)
print("Memory Need: ", arr.nbytes)



[10 20 30 40 50]
Type       :  <class 'numpy.ndarray'>
Shape      :  (5,)
Dimension  :  1
Element type:  int32
Memory Need:  20


In [12]:
# List to ndarray create

mix_lst = [10, 50.55, "Kz", True]

arr = np.array(mix_lst)

# arr = arr.astype(int32) # -> this show error

print("Dimension: ", arr.ndim)
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Element type: ", arr.dtype)   # <u32 

print("Total memory Need: ", arr.nbytes)




Dimension:  1
Shape:  (4,)
Size:  4
Element type:  <U32
Total memory Need:  512


In [ ]:
# Example: List to ndarray

lst_mix = [10, 20, [30.5, 40.5, 50.5], 60, 70]

arr = np.array(lst_mix)  # ValueError

print(arr)



ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [19]:
# Example: List to ndarray

matrix = [
    [10, 20, 30],
    [40, 40, 60]
]

arr = np.array(matrix, dtype = np.int32)
print(arr)

print("Dimension: ", arr.ndim)
print("Shape: ", arr.shape)

print("Size: ", arr.size)
print("Element type: ", arr.dtype)
print("Totla memory: ", arr.nbytes)


[[10 20 30]
 [40 40 60]]
Dimension:  2
Shape:  (2, 3)
Size:  6
Element type:  int32
Totla memory:  24


### 2. tuple to ndarray

In [26]:
# tuple to ndarray:

tpl = (10, 20, 30, 40, 50)

arr = np.array(tpl, dtype = np.int8)
print(arr)
print(type(arr))

print("Element type: ", arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
Element type:  int8


### 3. set to ndarry

In [ ]:
# Set to ndarray

# - ndarray -> set's all element count a single elment.

st = {1,2,3,4}

arr = np.array(st)

print(arr)  # print as single value
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Element type: ", arr.dtype) # object


# object to convert to int64
# if we try to convert another type then it's generate error

arr = arr.astype(np.int64)
prit(arr)


{1, 2, 3, 4}
Shape:  ()
Dimension:  0
Element type:  object


TypeError: int() argument must be a string, a bytes-like object or a real number, not 'set'

In [ ]:
# To solve the above problem(convert set to int64)

# 1st convert set to list 

st = {1,2,3,4}

arr = np.array(list(st))

print(arr)
print("Element type: ", arr.dtype)

# convert int64 to float32

arr = arr.astype(np.float32)
print(arr)
print("Element type: ", arr.dtype)


### NOTE-> in set we can't directly convert one data type to another

[1 2 3 4]
Element type:  int64
[1. 2. 3. 4.]
Element type:  float32


### 4. dic to ndarray

In [53]:
# dic to ndarray

# dic has keys, values , items

dct = {
    "a": 10,
    "b": 20,
    "c": 30
}

# first keys to ndarray
# for keys first convert to list
keys = dct.keys()
arr_keys = np.array(list(keys))

print(arr_keys)

print("Element type: ", arr_keys.dtype)  # <u1 (The keys contain one charcters)


# values to ndarray
values = dct.values()

arr_vals = np.array(list(values))
print(arr_vals)
print("Elment type of value: ", arr_vals.dtype)


['a' 'b' 'c']
Element type:  <U1
[10 20 30]
Elment type of value:  int64


In [54]:
# dic to ndarray

# dic has keys, values , items

dct = {
    "ab": 10,
    "b": 20,
    "c": 30.0
}

# first keys to ndarray
# for keys first convert to list
keys = dct.keys()
arr_keys = np.array(list(keys))

print(arr_keys)

print("Element type: ", arr_keys.dtype)  # <u2 (Because the keys contain 2 characters)


# values to ndarray
values = dct.values()

arr_vals = np.array(list(values))  # float64 (values has a float value)
print(arr_vals)
print("Elment type of value: ", arr_vals.dtype)


['ab' 'b' 'c']
Element type:  <U2
[10. 20. 30.]
Elment type of value:  float64


In [ ]:
# dic to ndarray

# dic has keys, values , items

dct = {
    "ab": 10,
    "b": "h",
    "ccc": 30.0
}

# first keys to ndarray
# for keys first convert to list
keys = dct.keys()
arr_keys = np.array(list(keys))

print(arr_keys)

print("Element type: ", arr_keys.dtype)  # <u3 (keys contains 3 characters)


# values to ndarray
values = dct.values()

arr_vals = np.array(list(values), dtype = np.int32)  # we can't convert string to int32
print(arr_vals)
print("Elment type of value: ", arr_vals.dtype)


['ab' 'b' 'ccc']
Element type:  <U3


ValueError: invalid literal for int() with base 10: 'h'