## Topic: ndarray Creation from Scratch

### OUTCOMES

- 1. np.zeros(shape) 
    - np.zeros_like(existing_array)

- 2. np.ones(shape) 
    - np.ones_like(existing_array)

- 3. np.empty(shape) 
    - np.empty_like(existing_array)

- 4. np.full(shape,num) 
    - np.full_like(existing_array,num)


### 1. np.zeros(shape) and np.zeros_like(existing_array)

- np.zeros(shape):

    - Create ndarray with initialization zero.

    - shape = shape of the array (2,3), (2,3,4), (1) in a tuple format.

- np.zeros_like(existing array)
    - function returns a new array of zeros having the same shape, data type, and memory layout as a given input array.


In [2]:
import numpy as np

In [4]:
# Example: np.zeros(shape)

# 2-d array:

arr = np.zeros((4,3))   # 4 = rows and 3 = columns

print(arr)

print("Element type: ", arr.dtype)   # Default type => float64

# convert float64 to int8

arr = arr.astype(np.int8)

print("Element type: ", arr.dtype) # int8
print("Dimension: ", arr.ndim) 
print("Shape: ", arr.shape)
print("Total Memory occupied: ", arr.nbytes) 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Element type:  float64
Element type:  int8
Dimension:  2
Shape:  (4, 3)
Total Memory occupied:  12


In [ ]:
# Example: np.zeors_like(existing_array)
# return existing_array shape, data type but all values are initialization with zeros.

arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]]
)


print("Elements type: ", arr2.dtype)
print("Shape: ", arr2.shape)

# convert arr2 all values into zero
zero_arr2 = np.zeros_like(arr2)

print(zero_arr2)

print("Elements type: ", zero_arr2.dtype)
print("Shape: ", zero_arr2.shape)



### NOTE: 
#    np.zeros_like : return same shape and dtype 

Elements type:  int64
Shape:  (3, 3)
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Elements type:  int64
Shape:  (3, 3)


### 2. np.ones(shape) and np.ones_like(existing_array)

- np.ones(shape):
    - Create array with initialization one

In [ ]:
# Example: np.ones(shape)

# 1-d :
arr1 = np.ones(1)
print(arr1)

print("Dimension: ", arr1.ndim)
print("Element type: ", arr1.dtype)

# convert float64 to int32

arr1 = arr1.astype(np.int32)
print("Element type:", arr1.dtype)


[1.]
Dimension:  1
Element type:  float64
Element type: int32


In [7]:
# np.ones_like(existing_array)
# return same shape and dtype of existing array but all elements initialize one.

arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80]
]

)
print("Array :\n", arr2)
print("Element type: ", arr2.dtype)
print("Shape: ", arr2.shape)

# now replace all elements to one but same shape, dtype int32
arr2 = np.ones_like(arr2, dtype = np.int32)

print("Array one: \n", arr2)
print("Shape: ", arr2.shape)
print("Element type: ", arr2.dtype)


Array :
 [[10 20 30 40]
 [50 60 70 80]]
Element type:  int64
Shape:  (2, 4)
Array one: 
 [[1 1 1 1]
 [1 1 1 1]]
Shape:  (2, 4)
Element type:  int32


### 3. np.empty(shape) and np.empty_like(existing_array)

- Create an ndarray with initialization empty(near to zero)

In [ ]:
# np.empty(shape)

arr = np.empty((2,3,3))   # 2 = depth , 3 = each depth rows and 3 = each depth column
print(arr)
print("Dimension: ", arr.ndim)
print("Shape: ", arr.shape)



[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [6.23047842e-307 8.45593934e-307 7.56593017e-307]
  [1.11258854e-306 1.11261502e-306 1.42410839e-306]]

 [[7.56597770e-307 6.23059726e-307 1.42419530e-306]
  [1.11261027e-306 1.06809996e-306 1.37962456e-306]
  [1.29060871e-306 1.29061414e-306 1.42410974e-306]]]
Dimension:  3
Shape:  (2, 3, 3)


In [ ]:
# np.empty(existing_array)
arr2 = np.empty_like(arr2, dtype = np.int16)
print(arr2)

# generate random values

[[[    0     0     0]
  [    0 13344 30446]
  [  604     0 13824]]

 [[30446   604     0]
  [13184 30446   604]
  [    0 28258 11883]]]


### 4. np.full(shape) and np.full_like(existing_array)

- np.full(shape,num):
    - Create ndarray with specific number.


In [ ]:
# np.full(shape)

arr3 = np.full((2,4,3),6, dtype = np.int8) # all elements = 6

print(arr3)
print("Shape: ", arr3.shape)
print("Element type: ", arr3.dtype)
print("Size : ", arr3.size)
print("one element need: ", arr3.itemsize)
print("Total bytes: ", arr3.nbytes)

[[[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]]
Shape:  (2, 4, 3)
Element type:  int8
Size :  24
one element need:  1
Total bytes:  24


In [ ]:
# np.full_like(existing_array)

arr = np.full_like(arr3,2,dtype= np.float32)  # existing array = arr3 and specific num = 2

print(arr)
print("Shape: ", arr.shape)

print("size: ", arr.size)

print("Element type: ", arr.dtype)

print("Each item memory occupied: ", arr.itemsize)

print("Total Memory occupied: ", arr.nbytes)


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
Shape:  (2, 4, 3)
size:  24
Element type:  float32
Each item memory occupied:  4
Total Memory occupied:  96


In [ ]:
# Create with initialization infinite values

arr_inf = np.full((2,3),np.inf)

print(arr_inf)

print("Dimension: ", arr_inf.ndim)
print("Element type: ", arr_inf.dtype)
print("Size: ", arr_inf.size)
print("individual Item: ", arr_inf.itemsize)
print("Total Memory occupied: ", arr_inf.nbytes)


[[inf inf inf]
 [inf inf inf]]
Dimension:  2
Element type:  float64
Size:  6
individual Item:  8
Total Memory occupied:  48


#### one short

In [18]:
# array
arr2 = np.array([
    [10, 20, 30, 40], 
    [15, 25, 35, 45],
    [50, 60, 70, 80],
    [65, 75, 85, 95]
])

print("Array: \n", arr2)
print("Type: ", type(arr2))
print("Element type: ", arr2.dtype)


Array: 
 [[10 20 30 40]
 [15 25 35 45]
 [50 60 70 80]
 [65 75 85 95]]
Type:  <class 'numpy.ndarray'>
Element type:  int64


In [12]:
# zeros

arr_zero = np.zeros((2,3))

print(arr_zero)
print("Element type: ", arr_zero.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
Element type:  float64


In [14]:
# ones_like
arr_one = np.ones_like(arr2)

print("Arrary one: \n", arr_one)
print("Element type: ", arr_one.dtype)

Arrary one: 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Element type:  int64


In [16]:
# full 
arr_full = np.full((3,5), 10, dtype=np.int32)

print("Array Full : \n", arr_full)

print("Element type: ", arr_full.dtype)

Array Full : 
 [[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
Element type:  int32


In [17]:
# inifinite 

arr_inf = np.full_like(arr2, np.inf)

print("Array infinite: \n", arr_inf)

print("Element type: ", arr_inf.dtype)

Array infinite: 
 [[-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808]]
Element type:  int64


c:\Users\HP\anaconda3\Lib\site-packages\numpy\_core\numeric.py:457: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(res, fill_value, casting='unsafe')
