## Topic: ndarray generates/creation with random values

### OUTCOMES

- 1. np.random.rand(shape) 

- 2. np.random.randint(range, shape)

- 3. np.random.uniform(range, shape)


In [3]:
import numpy as np

- These full function return random numbers and we can't predict the next numbers.

- Use in ML:
    - initializing model weights.
    - creating test datasets.

### 1. np.random.rand() 

- Generate random number float in between 0-1 that are uniform distribution.

In [1]:
# syntax of : np.random.rand()
'''  
 - np.random.rand(shape) 
 

'''

'  \n - np.random.rand(shape) \n \n\n'

In [15]:
# Example: for 1-d 

arr1 = np.random.rand(5)  # generate 5 random numbers in between 0-1.

print(arr1)
print(type(arr1))

print("Element type: ", arr1.dtype)
print("Dimension: ", arr1.ndim)
print("shape: ", arr1.shape)



[0.26738608 0.78955838 0.32011379 0.80732581 0.10275981]
<class 'numpy.ndarray'>
Element type:  float64
Dimension:  1
shape:  (5,)


In [ ]:
# Example: random.rand()-> for 2-d array
# Each dimension is given as a separate argument.

arr2 = np.random.rand(3,2)  # here 3 = rows and 2 = columns  

print(arr2)

print("Dimension: ", arr2.ndim)
print("shape: ", arr2.shape)


[[0.8554755  0.22863295]
 [0.13697469 0.82734912]
 [0.43223457 0.7279741 ]]
Dimension:  2
shape:  (3, 2)


In [ ]:
# np.random.rand(): for 3-d ndarray

arr3 = np.random.rand(2,3,4)  # 2 = depth, 3 = each depth rows and 4 = each depth columns
print(arr3)

print("Dimension: ", arr3.ndim)
print("Shape: ", arr3.shape)
print("Element type: ", arr3.dtype)


[[[0.37344867 0.78819341 0.98956264 0.90477995]
  [0.45568853 0.04968372 0.66505925 0.97447846]
  [0.01251463 0.9547787  0.74746481 0.08636069]]

 [[0.20579619 0.45022228 0.97346389 0.44549889]
  [0.85611179 0.12792555 0.72581758 0.01498471]
  [0.00765873 0.84458092 0.09072249 0.86300601]]]
Dimension:  3
Shape:  (2, 3, 4)
Element type:  float64


### 2. np.random.randint()

In [ ]:
# syntax :
''''  
np.random.randint(start,end,size) -> create an interger random numbers in a given range.

- here,
    - start -> starting number to generated random numbers (include)
    - end  -> end of the random number(no include)
    - size -> size of the ndarray (in tuple format)

'''

In [9]:
# Example: np.random.randint()

# for integer numbers

arr1 = np.random.randint(5)  # generate a random number 0-4 (5 is not include)

print(arr1)
# print("Dimension: ", arr1.ndim)
print(type(arr1))


# another way
arr11 = np.random.randint(5,10)  # generate a random number 5-9.
print(arr11)


0
<class 'int'>
5


In [ ]:
# for 1-d array

arr1 = np.random.randint(10, size=(1,))

print("Array: \n", arr1)
print("Type: ", type(arr1))

print("Dimension: ", arr1.ndim)


# arr1 = np.random.randint(10,100, size=(1,))
# print("Array: \n", arr1)
# print("Type: ", type(arr1))

Array: 
 [9]
Type:  <class 'numpy.ndarray'>
Dimension:  1
Array: 
 [26]
Type:  <class 'numpy.ndarray'>


In [ ]:
# for 2-d array: np.random.randint(start,end, size=)


arr2 = np.random.randint(10,50,size= (4,5))  # generate (4,5) shape random numbers in range 10 to 49

print(arr2)

print("Dimension: ",arr2.ndim)
print("Element data type: ", arr2.dtype)


# NOTE
# - np.random.randint() : create ndarray with random integer in specific Range.

[[41 37 37 20 17]
 [33 16 10 43 26]
 [34 21 27 38 38]
 [20 21 10 43 42]]
Dimension:  2
Element data type:  int32


### 3. np.random.uniform()

- syntax:
    - np.random.uniform(start,end, size)

    - here : end = not include (exclusive)

- Generate floating random numbers in range of start and end.
- Returns: Array of random floats from uniform distribution

In [ ]:
# Example: np.random.uniform(start,end,size)

# for single number
arr1 = np.random.uniform(6) # generate a float random number in between 0-5

print(arr1)
print("Type: ", type(arr1))

4.91127382316472
Type:  <class 'float'>


In [ ]:
# for 2-d array : np.random.uniform(start,end,size)

arr2 = np.random.uniform(4,20,size = (3,4))  # 3 = rows and 4 = columns

print(arr2)
print("Dimension: ", arr2.ndim)
print("Element type: ",arr2.dtype)

# convert float64 to int32
arr2 = arr2.astype(np.int32)

print(arr2)
print("Dimension: ", arr2.ndim)
print("Element type: ", arr2.dtype)



[[ 7.94808524  6.36409747  9.64832847 14.6897642 ]
 [18.26351372  7.5231286  19.55946357 19.26058361]
 [16.72590719 19.40965571 16.42150187 14.21718582]]
Dimension:  2
Element type:  float64
[[ 7  6  9 14]
 [18  7 19 19]
 [16 19 16 14]]
Dimension:  2
Element type:  int32


#### ONE SHORT

In [ ]:
# np.random.rand(n) -> generate n random number in between 0-1

# np.random.randint(range, shape) -> generate integer random number in given range with specific shape

# np.random.uniform() -> Generate float numbers in given range with specific shape

In [1]:
import numpy as np

In [13]:
# np.random.rand(num)
arr1 = np.random.rand(6)

print(arr1)

arr1 = np.random.rand(3,2)
print(arr1)

[0.93223166 0.02078394 0.50662458 0.40129216 0.29127008 0.58181706]
[[0.85705127 0.75639196]
 [0.97939984 0.03921237]
 [0.65487598 0.86957101]]


In [ ]:
# np.random.randint(range, shape)
arr2 = np.random.randint(5,20, size=(5,3))

arr2

array([[12,  6,  6],
       [ 9, 10,  8],
       [19,  9,  5],
       [14,  6, 12],
       [18, 13,  9]], dtype=int32)

In [ ]:
# np.random.uniform(range,shape)

arr = np.random.uniform(1,15, size=(7,4))

print(arr)


[[ 8.59783215 14.09671121  9.05029662 13.63228109]
 [ 9.22922809 11.23858634  9.62692178  2.60542261]
 [13.37333083 12.67702897  9.6183683   5.90853802]
 [ 2.24020864  4.93898697 14.79393269  7.87463427]
 [ 5.5358617   5.74945036  2.82992577 12.79986335]
 [10.24299684  4.79729938 14.05974251 11.71549391]
 [ 8.10877941  3.61755972  9.30119216  4.3887609 ]]
