## Topic: ndarray generation/creation with random values

### OUTCOMES

- 1. np.random.rand() 

- 2. np.random.randint()

- 3. np.random.uniform()


In [1]:
import numpy as np

- These full function return random numbers and we can't predict the next numbers

- Use in ML:
    - initializing model weights.
    - creating test datasets.

### 1. np.random.rand() 

- Generate random number float in between 0-1 that are uniform distribution.

In [ ]:
# syntax of : np.random.rand()
'''  
 - np.random.rand(d1,d2,d3) 
 - Takes dimensions as separate arguments

'''

In [15]:
# Example: for 1-d 

arr1 = np.random.rand(5)  # generate 5 random numbers in between 0-1.

print(arr1)
print(type(arr1))

print("Element type: ", arr1.dtype)
print("Dimension: ", arr1.ndim)
print("shape: ", arr1.shape)



[0.26738608 0.78955838 0.32011379 0.80732581 0.10275981]
<class 'numpy.ndarray'>
Element type:  float64
Dimension:  1
shape:  (5,)


In [ ]:
# Example: random.rand()-> for 2-d array
# Each dimension is given as a separate argument.

arr2 = np.random.rand(3,2)  # generate 3 = rows and 2 = columns random numbers 

print(arr2)

print("Dimension: ", arr2.ndim)
print("shape: ", arr2.shape)


[[0.8554755  0.22863295]
 [0.13697469 0.82734912]
 [0.43223457 0.7279741 ]]
Dimension:  2
shape:  (3, 2)


In [ ]:
# np.random.rand(): for 3-d ndarray

arr3 = np.random.rand(2,3,4)  # 2 = depth, 3 = each depth rows and 4 = each depth columns
print(arr3)

print("Dimension: ", arr3.ndim)
print("Shape: ", arr3.shape)
print("Element type: ", arr3.dtype)


[[[0.37344867 0.78819341 0.98956264 0.90477995]
  [0.45568853 0.04968372 0.66505925 0.97447846]
  [0.01251463 0.9547787  0.74746481 0.08636069]]

 [[0.20579619 0.45022228 0.97346389 0.44549889]
  [0.85611179 0.12792555 0.72581758 0.01498471]
  [0.00765873 0.84458092 0.09072249 0.86300601]]]
Dimension:  3
Shape:  (2, 3, 4)
Element type:  float64


### 2. np.random.randint()

In [ ]:
# syntax :
''''  
np.random.randint(start,end,size) -> create an interger random numbers in a given range.

- here,
    - start -> starting number to generated random numbers (include)
    - end  -> end of the random number(no include)
    - size -> size of the ndarray

'''

In [ ]:
# Example: np.random.randint()

# for integer numbers

arr1 = np.random.randint(5)  # generate a random number 0-4 (5 is not include)

print(arr1)
# print("Dimension: ", arr1.ndim)
print(type(arr1))


# another way
arr11 = np.random.randint(5,10)  # generate a random number 5-9.
print(arr11)


1
<class 'int'>
9


In [ ]:
# for 2-d array: np.random.randint(start,end, size)


arr2 = np.random.randint(10,50,size= (4,5))  # generate (4,5) shape random numbers in range 10 to 49

print(arr2)

print("Dimension: ",arr2.ndim)
print("Element data type: ", arr2.dtype)


# NOTE
# - np.random.randint() : create ndarray with random integer in specific Range.

[[41 37 37 20 17]
 [33 16 10 43 26]
 [34 21 27 38 38]
 [20 21 10 43 42]]
Dimension:  2
Element data type:  int32


### 3. np.random.uniform()

- syntax:
    - np.random.uniform(start,end, size)

    - here : end = not include (exclusive)

- Generate floating random numbers in range of start and end.
- Returns: Array of random floats from uniform distribution

In [ ]:
# Example: np.random.uniform(start,end,size)

# for single number
arr1 = np.random.uniform(6) # generate a float random number in between 0-5

print(arr1)
print("Type: ", type(arr1))

4.91127382316472
Type:  <class 'float'>


In [54]:
# for 2-d array : np.random.uniform(start,end,size)

arr2 = np.random.uniform(4,20,size = (3,4))

print(arr2)
print("Dimension: ", arr2.ndim)
print("Element type: ",arr2.dtype)

# convert float64 to int32
arr2 = arr2.astype(np.int32)
print(arr2)
print("Dimension: ", arr2.ndim)
print("Element type: ", arr2.dtype)



[[ 7.94808524  6.36409747  9.64832847 14.6897642 ]
 [18.26351372  7.5231286  19.55946357 19.26058361]
 [16.72590719 19.40965571 16.42150187 14.21718582]]
Dimension:  2
Element type:  float64
[[ 7  6  9 14]
 [18  7 19 19]
 [16 19 16 14]]
Dimension:  2
Element type:  int32
