## Topic: 5. ndarry generation with range

### OUTCOMES

- 1. np.arange()

- 2. np.arange() with reshape()

- 3. np.linspace()

- 4. np.lognspace()

### 1. np.arange()

- Generate deterministic sequences

- syntax:
    - np.range(start,end,step,dtype= none)

    - here,
        - start => 0 (by defalut) and is't include
        - end   => len(array) and it's not include (exclusive)
        - step  => 1  

- np.arange() return 1-d array.
- it's can't product the 2-d array. if we need 2-d array then we use .reshape().

In [1]:
import numpy as np

In [ ]:
# np.arange() -> similare to range 

# 1-d:
arr1 = np.arange(1,10)  # give the numbers in between 1-9
print(arr1)

print("Dimension: ", arr1.ndim)

print("Size: ", arr1.size)
print("Element type: ", arr1.dtype)


# case - 2 for steps
arr1 = np.arange(1,20,2, dtype = np.int8)  # steps = 2
print(arr1)

print("Dimension: ", arr1.ndim)

print("Size: ", arr1.size)
print("Element type: ", arr1.dtype)



[1 2 3 4 5 6 7 8 9]
Dimension:  1
Size:  9
Element type:  int64
[ 1  3  5  7  9 11 13 15 17 19]
Dimension:  1
Size:  10
Element type:  int8


In [ ]:
# 2-d : for np.arange()

arr2 = np.arange(1,11,1, (2,5))

print(arr2)


# NOTE: 
# - We can't directly create 2-d array by using np.arange()

TypeError: Cannot interpret '2' as a data type

### 2. np.range() with reshape()

In [ ]:
# reshape() -> changing the structure of an array without chaning it's data.

# example: 
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)
print("Dimension: ", arr.ndim)

# use reshape

arr1 = arr.reshape(3,3)  # 3 = rows and 3 = columns

print(arr1)
print("Dimension: ", arr1.ndim)


# NOTE:
# - reshape(rows, cols) must be equal to the total numbers of elements

[1 2 3 4 5 6 7 8 9]
Dimension:  1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension:  2


In [ ]:
# reshape with np.arange()
# 2-d
arr2 = np.arange(1,13).reshape(3,4)

print(arr2)
print("Dimension: ", arr2.ndim)
print("shape: ", arr2.shape)
print("Element data type: ", arr2.dtype)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension:  2
shape:  (3, 4)
Element data type:  int64


In [ ]:
# reshape with np.arange()

# 3-d

arr3 = np.arange(1,25,dtype = np.int16).reshape(2,3,4)   # 2 = depth , 3 = each depth rows and 4 = each depth columns

print(arr3)
print("Dimension: ", arr3.ndim)
print("size: ", arr3.size)
print("Element type: ", arr3.dtype)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Dimension:  3
size:  24
Element type:  int16


In [33]:
# reshape with np.arange()

arr2 = np.arange(2,21,2)

print(arr2)
print("Dimension: ", arr2.ndim)


# apply reshape

arr2 = arr2.reshape(2,5)
print(arr2)
print("Dimension: ", arr2.ndim)
print("Shape: ", arr2.shape)


[ 2  4  6  8 10 12 14 16 18 20]
Dimension:  1
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
Dimension:  2
Shape:  (2, 5)


### 3. np.linspace()

- linearly generated numbers

- syntax:
    - np.linspace(start,stop,step,total_num)

    - here,
        - start = 0 (include)
        - stop = length of array (include)
        - total_num = Numbers that we want to generated


In [35]:
# Example: np.linspace(star,stop,step, total_num)


arr1 = np.linspace(1,5,5) # start = 1, stop = 5 and total number genrator = 5
print(arr1)

print("Dimension: ", arr1.ndim)


[1. 2. 3. 4. 5.]
Dimension:  1


In [37]:
# 2-d ndarray

arr2 = np.linspace(1,12,num = 12).reshape(3,4)

print(arr2)


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [ ]:
arr = np.linspace(1,10, num = 5)
print(arr)  # generate 5 numbers in between 1-10 but nums are linearly seperator.

[ 1.    3.25  5.5   7.75 10.  ]


In [39]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
'''  
start = 0 (include)
end = 10  (include)
total number = 5

5 - 2 = 3

| 0  | 2.5 | 5.0 | 7.5 | 10 |


- here, 
  2.5 - 0 = 2.5
  5.0 - 2.5 = 2.5
  7.5 - 2.5 = 5.0
  10.0 - 2.5 = 7.5
  7.5 + 2. 5 = 10.0


'''

### 4. np.lognspace()

In [ ]:
# Syntax of np.lognspace()
# np.lognspace(start,stop,total_nums, base=10)
# stop -> include

arr = np.logspace(0,4,5)
print(arr)

'''
start num = 0 (include)

stop num = 10

wihtin 0 to 10 creates 5 , 10 base log

''' 



[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


In [8]:
# when change the default base to 2

arr2 = np.logspace(0,10,6, base = 2).reshape(2,3)

print(arr2)

print("Dimension: ", arr2.ndim)

print("Element type :", arr2.dtype)

print("Shape : ", arr2.shape)



[[1.000e+00 4.000e+00 1.600e+01]
 [6.400e+01 2.560e+02 1.024e+03]]
Dimension:  2
Element type : float64
Shape :  (2, 3)
