## Topic: ndarry generates with range

### OUTCOMES

- 1. np.arange()

- 2. np.arange() with reshape()

- 3. np.linspace()

- 4. np.lognspace()

### 1. np.arange()

- Generate deterministic sequences (we can predict the next numbers)

- syntax:
    - np.range(start,end,step,dtype= none)

    - here,
        - start => 0 (by defalut) and is't include
        - end   => len(array) and it's not include (exclusive)
        - step  => 1  

- np.arange() return 1-d array.
- it's can't provide the 2-d array. if we need 2-d array then we use .reshape() function

In [1]:
import numpy as np

In [ ]:
# np.arange() -> similare to range 

# 1-d:
arr1 = np.arange(1,10)  # give the numbers in between 1-9
print(arr1)

print("Dimension: ", arr1.ndim)

print("Size: ", arr1.size)
print("Element type: ", arr1.dtype) # default behavior


# case - 2 for steps
arr1 = np.arange(2,20,2, dtype = np.int8)  # steps = 2
print(arr1) 

print("Dimension: ", arr1.ndim)

print("Size: ", arr1.size)
print("Element type: ", arr1.dtype) # customize the default behavior



[1 2 3 4 5 6 7 8 9]
Dimension:  1
Size:  9
Element type:  int64
[ 2  4  6  8 10 12 14 16 18]
Dimension:  1
Size:  9
Element type:  int8


In [ ]:
# 2-d : for np.arange()

arr2 = np.arange(1,11,1, (2,5))

print(arr2)


# NOTE: 
# - We can't directly create 2-d array by using np.arange()

TypeError: Cannot interpret '2' as a data type

### 2. np.range() with reshape()

In [ ]:
# reshape() -> changing the structure of an array without chaning it's data.

# example: 
arr = np.array([1,2,3,4,5,6,7,8,9])

print("Array1 : \n", arr)
print("Dimension: ", arr.ndim)

# use reshape

arr1 = arr.reshape(3,3)  # 3 = rows and 3 = columns

print("Array2: \n",arr1)
print("Dimension: ", arr1.ndim)

# the other posible way to reshape
# arr1 = arr.reshape(1,9)
# arr1 = arr.reshape(9,1)

# NOTE:
# - reshape(rows, cols) must be equal to the total numbers of elements

Array1 : 
 [1 2 3 4 5 6 7 8 9]
Dimension:  1
Array2: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension:  2


In [ ]:
# reshape with np.arange()
# 2-d
arr2 = np.arange(1,13).reshape(3,4)   # start num = 1 and end num = 12 and step = 1

print(arr2)
print("Dimension: ", arr2.ndim)
print("shape: ", arr2.shape)
print("Element data type: ", arr2.dtype)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension:  2
shape:  (3, 4)
Element data type:  int64


In [ ]:
# reshape with np.arange()

# 3-d

arr3 = np.arange(1,25,dtype = np.int16).reshape(2,3,4)   # 2 = depth , 3 = each depth rows and 4 = each depth columns

print(arr3)
print("Dimension: ", arr3.ndim)
print("size: ", arr3.size)
print("Element type: ", arr3.dtype)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Dimension:  3
size:  24
Element type:  int16


In [33]:
# reshape with np.arange()

arr2 = np.arange(2,21,2)

print(arr2)
print("Dimension: ", arr2.ndim)


# apply reshape

arr2 = arr2.reshape(2,5)
print(arr2)
print("Dimension: ", arr2.ndim)
print("Shape: ", arr2.shape)


[ 2  4  6  8 10 12 14 16 18 20]
Dimension:  1
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
Dimension:  2
Shape:  (2, 5)


### 3. np.linspace(range, num = n)

- linearly generated numbers

- syntax:
    - np.linspace(start,stop,step,total_num)

    - here,
        - start = 0 (include)
        - stop = length of array (include)
        - total_num = Numbers that we want to generated


In [35]:
# Example: np.linspace(star,stop,step, total_num)


arr1 = np.linspace(1,5,5) # start = 1, stop = 5 and total number genrator = 5
print(arr1)

print("Dimension: ", arr1.ndim)


[1. 2. 3. 4. 5.]
Dimension:  1


In [5]:
arr = np.linspace(1,5,num = 3)
print(arr)

[1. 3. 5.]


In [4]:
arr = np.linspace(1,10, num = 5)
print(arr)  # generate 5 numbers in between 1-10 but nums are linearly seperator.

[ 1.    3.25  5.5   7.75 10.  ]


In [37]:
# 2-d ndarray

arr2 = np.linspace(1,12,num = 12).reshape(3,4)

print(arr2)


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [ ]:
'''  
start = 0 (include)
end = 10  (include)
total number = 5

- Two numbers are include (star - 0 and end- 10) 
5 - 2 = 3

| 0  | 2.5 | 5.0 | 7.5 | 10 |


- here, 
  2.5 - 0 = 2.5
  5.0 - 2.5 = 2.5
  7.5 - 2.5 = 5.0
  10.0 - 2.5 = 7.5
  7.5 + 2. 5 = 10.0


'''

In [9]:
arr2 = np.linspace(1, 12,num=5).reshape(3,4)

print(arr2)

ValueError: cannot reshape array of size 5 into shape (3,4)

### 4. np.lognspace()

In [ ]:
# Syntax of np.lognspace()
# np.lognspace(start,stop,total_nums, base=10)
# stop -> include

arr = np.logspace(0,4,5)
print(arr)

'''
start num = 0 (include)

stop num = 10

wihtin 0 to 10 creates 5 , 10 base log

''' 



[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


In [10]:
# when change the default base to 2

arr2 = np.logspace(0,10,num = 6, base = 2).reshape(2,3)

print(arr2)

print("Dimension: ", arr2.ndim)

print("Element type :", arr2.dtype)

print("Shape : ", arr2.shape)



[[1.000e+00 4.000e+00 1.600e+01]
 [6.400e+01 2.560e+02 1.024e+03]]
Dimension:  2
Element type : float64
Shape :  (2, 3)


### ONE SHORT

- These are function create or return 1-d array and we will determine the next generate numbers.
- if we need to convert 1-d array to 2-d array then we use reshape()
- when use reshape() then be carefull because number of generated nums must be same (in 1-d and 2-d).

In [11]:
# np.arange(range)

arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [15]:
# np.arange(range).reshape()

arr1 = np.arange(1,11).reshape(2,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
# np.linspace(range, num=n)

arr2 = np.linspace(2,20, num = 6)

print(arr2)

[ 2.   5.6  9.2 12.8 16.4 20. ]


In [ ]:
# np.linspace(range, num= n).reshape()

arr2 = np.linspace(1,20, num = 30).reshape(5,6)

print("Array: \n", arr2)
print("\nTotal numbers: ", arr2.size)

# num == shape
# here = 30
# shape = 5,6  (5*6 = 30)

# 30 == 30 (it's posible)

Array: 
 [[ 1.          1.65517241  2.31034483  2.96551724  3.62068966  4.27586207]
 [ 4.93103448  5.5862069   6.24137931  6.89655172  7.55172414  8.20689655]
 [ 8.86206897  9.51724138 10.17241379 10.82758621 11.48275862 12.13793103]
 [12.79310345 13.44827586 14.10344828 14.75862069 15.4137931  16.06896552]
 [16.72413793 17.37931034 18.03448276 18.68965517 19.34482759 20.        ]]

Total numbers:  30


In [24]:
# np.logspace(range, num = n, base = 10)

arr1 = np.logspace(1,10, num=5, base= 10)

print(arr1)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [ ]:
# np.logspace(range, num = n, base = 10).reshape()


arr2 = np.logspace(2, 15, num = 20, base = 2).reshape(4,5)

print(arr2)


# start num = 2 and end num = 15 and step = 1

# total generate nums = 15

# reshape = 4,5 (so 4*5 = 20)


[[4.00000000e+00 6.42728981e+00 1.03275136e+01 1.65944807e+01
  2.66643842e+01]
 [4.28449312e+01 6.88441975e+01 1.10620402e+02 1.77747346e+02
  2.85608427e+02]
 [4.58922033e+02 7.37406227e+02 1.18488088e+03 1.90389321e+03
  3.05921835e+03]
 [4.91562074e+03 7.89852978e+03 1.26915350e+04 2.03930434e+04
  3.27680000e+04]]


In [ ]:
# Quiz:
''' 

What is the output of list(filter(lambda x: x%2==0, [1,2,3,4]))?

A. [1,3]

B. [2,4]

C. [1,2,3,4]

D . []

'''