## Topic: Create Matrix for linear Algebra

### OUTCOMES

- 1. Diagonal Matrix

- 2. Identity Matrix

### - 1. Diagonal Matrix

- A square matrix with zeros everywhere except for the main diagonal.

    - square matrix: numbers of rows and columns are equal

- Syntax:
    - np.diag( v, k = 0)

    - here,     
        - v = number of values
        - k = 0 (Main diagonal)
        - k > 0 (upper diagonal)-> shifted diagonal into upper(positive)
        - k < 0 (lower diagonal)-> shifted diagonal into lowe (negative) 

In [ ]:
# matrix Representation of Diagonal Marix:
'''  
| 2  0  0 |
| 0  4  0 |
| 0  0  6 |
 
'''
# here, main diagonal path -> 2 , 4, 6

In [1]:
import numpy as np

In [ ]:
# Example: Diagonal Matrix 

arr2 = np.diag([2,4,6], k=0)  # here, 2,4,6 => main diagonal values

print(arr2)

print("Element type: ", arr2.dtype)

[[2 0 0]
 [0 4 0]
 [0 0 6]]
Element type:  int64


In [ ]:
# Example : Shifted Diagonal upper

arr2 = np.diag([1,2,3,4], k = 1)

print(arr2)


### NOTE:
# - A diagonal matrix must be a square matrix
# - here we only shift the values 

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [9]:
# Shifted Diagonal lower

# arr2 = np.diag([0,0,0],-1)

arr2 = np.diag([10,20,30], -1)

print(arr2)



[[ 0  0  0  0]
 [10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]]


In [ ]:
###  Extracting Diagonal from Matrix

arr = np.arange(1,13).reshape(3,4)

diagonal_arr = np.diag(arr)

print("Diagonal of arr: ",diagonal_arr)

print(arr)
# arr is not a diagonal matrix

Diagonal of arr:  [ 1  6 11]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Not diagonal matrix
# NOTE: -> if the matrix is not square


arr = np.arange(1,13).reshape(3,4)
print(arr)

print("Shape: ", arr.shape) # rows = 3 and columns = 4


arr_dia = np.diag(arr)
print(arr_dia)


# NOTE: here arr is not diagonal matrix

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape:  (3, 4)
[ 1  6 11]


### 2. Identity Matrix

- A special type of diagonal matrix where all main diagonal elements are 1.
- off-diagonal elements are zero(0)

- Must be a square matrix

- syntax:
    - 1. np.identity(n, dtype = float)

    - 2. np.eye(n,k=0,dtype = float)



In [ ]:
# Example : Identity Matrix with np.identity(n)
# np.identity(n)-> create square identity matrix

identity_mat = np.identity(3)

print(identity_mat)


# np.identity(2,3)-> show error (because 3 count as dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
###  Extracting identity from Matrix is not work -> no-diagonal must be zero

arr = np.arange(1,10).reshape(3,3)

id_arr = np.identity(arr)

print("Diagonal of arr: ",id_arr)

print(arr)
# arr is not a diagonal matrix

TypeError: only integer scalar arrays can be converted to a scalar index

#### np.eye(n,k=0,dtype=float)

- create square identity and non-square identity matrix

In [27]:
# Square identity: np.eye(n)

square_identity = np.eye(4,k=0,dtype=np.int8)

print(square_identity)
print("Shape: ", square_identity.shape)
print("Element type: ", square_identity.dtype)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Shape:  (4, 4)
Element type:  int8


In [31]:
# shifted or non-square identity matrix

arr = np.eye(4,3, k = 1) # shift to 2nd column (upper shifted)

print(arr)
print("shape: ", arr.shape)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape:  (4, 3)


In [32]:
# lower shifte 
arr = np.eye(4,3,k=-1,dtype=np.int8)
print(arr)

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
