## Topic: ndarray Indexing and Slicing

### OUTCOMES

- 1. Basic Indexing (1D, 2D, 3D)

- 2. Negative Indexing 

- 3. Basic slicing (1D, 2D, 3D)

- 4. .view() method

- 5. .copy() method


### 1. Basic Indexing (1D, 2D, 3D)

- Indexing:
    - Acces and modify the specific (single) element by using idexing.

In [1]:
import numpy as np

#### 1-d array indexing

In [ ]:
"""   
   ----------------------------------------------
   | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 |     <-- Array elements
   ------------------------------------------------
   | 0  | 1  | 2  | 3  | 4  | 5  | 6  | 7  | 8  |      <------ Positive idx
   -------------------------------------------------


"""

In [ ]:
arr1 = np.array([10,20,30,40,50,60,70,80,90])

# Access single specific element
element_30 = arr1[2]  # here 2-> idx
print("idx 2 element: ",element_30)

print("Idx 4 element: ", arr1[4]) # 50


# modify single element

arr1[5] = 500

print("Idx 5 element: ", arr1[5]) # 500


# deleted a single elmeent in 1-d array

arr_new = np.delete(arr1,5) # here, 5 - idx

print("Original array: ", arr1)
print("After delete new array: ", arr_new)



idx 2 element:  30
Idx 4 element:  50
Idx 5 element:  500
Original array:  [ 10  20  30  40  50 500  70  80  90]
After delete new array:  [10 20 30 40 50 70 80 90]


In [ ]:
# delete multiple elements

arr = np.delete(arr1, [2,3])   # here 2, 3 are idx 

print("Original array: ", arr1)
print("After delete new array: ", arr)


Original array:  [ 10  20  30  40  50 500  70  80  90]
After delete new array:  [ 10  20  50 500  70  80  90]


#### 2-d array indexing

In [ ]:
arr2 = np.arange(1,13).reshape(3,4)

print("Original array: \n",arr2)


Original array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# access the 2-d array element

# syntax : arr_name[row, column]

print(arr2[1,1])  # 1 = row idx and 1 = column idx 
print(arr2[1,2])  # 1 = row idx and 2 = colum idx  
print(arr2[0,0])


### NOTE-> ndarray idx start 0 (0-base idxing)

6
7
1


In [28]:
# modify the 2-d array element

arr2[0,0] = 100
print(arr2[0,0])

arr2[1,1] = 600
print(arr2[1,1])


print("Modify Array: \n", arr2)



100
600
Modify Array: 
 [[100   2   3   4]
 [  5 600   7   8]
 [  9  10  11  12]]


In [ ]:
# 2-d arrray elmeent delete (single, multiple)

# syntax : np.delete(arr,idx,axis)
# axis => 0 means row
# axis => 1 means column

# Delete single 2-d array element

arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [15, 25, 35, 45]
])

print("Original array: \n", arr2)


# delete row
new_arr = np.delete(arr2,0,axis=0)  # 0-> row delete


print("After delete row: \n",new_arr)



Original array: 
 [[10 20 30 40]
 [50 60 70 80]
 [15 25 35 45]]
After delete row: 
 [[50 60 70 80]
 [15 25 35 45]]


In [ ]:
# 2-d arrray elmeent delete (single, multiple)

# syntax : np.delete(arr,idx,axis)
# axis => 0 means row
# axis => 1 means column

# Delete single 2-d array element

arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [15, 25, 35, 45]
])

print("Original array: \n", arr2)

# delete single column

new_arr = np.delete(arr2,1,axis=1)  # 1 idx column is deleted

print("After delete column: \n", new_arr)


Original array: 
 [[10 20 30 40]
 [50 60 70 80]
 [15 25 35 45]]
After delete column: 
 [[10 30 40]
 [50 70 80]
 [15 35 45]]


### 2. Negative Indexing 

In [ ]:
"""   
   -------------------------------------------------------
   | 10   | 20 |  30 | 40  | 50  | 60  | 70  | 80  | 90  |     <-- Array elements
   -------------------------------------------------------
   | -9  | -8  | -7  | -6  | -5  | -4  | -3  | -2  | -1  |      <------ negative idx
   --------------------------------------------------------

"""

In [45]:
# negative index for 1-d array:
# Negative idx start with -1

arr1 = np.arange(10,91,10)

print(arr1)
# print(arr1.ndim)

# access single element using negative idx

print(arr1[-1]) # last element

print(arr1[-9])


# modify
arr1[-9] = 900

arr1[-5] = 500

print("After modify: ", arr1)


# delete
arr_new = np.delete(arr1,-1)

print("After Deleted: ", arr_new)

[10 20 30 40 50 60 70 80 90]
90
10
After modify:  [900  20  30  40 500  60  70  80  90]
After Deleted:  [900  20  30  40 500  60  70  80]


### 3. Basic slicing (1D, 2D, 3D)

- Access and modify the multiple array elements
- Extract the subarray in the main array



#### Slicing for 1-d array
- syntax for 1-d:
    - arr_name[start_idx: end_idx: steps]

    - start_idx = 0 (default)
    - end_idx = len(arr) [default]
    - steps = 1 (default)

- remember that: 
    - end_idx is not include (exclusive)

    - ndarray follow 0-base indexing.


In [54]:
# 1-d array for slicing:

arr1 = np.array([1,2,3,4,5,6,7,8,9])

print("Original array: ", arr1)

# access the multiple array element or specific range or subarray

sub_arr = arr1[1:6:1] # 1 = start idx ; 6 = end idx(exclusive) ; 1 = steps
print(sub_arr)


print(arr1[5:9])

print(arr1[3:8:2])



Original array:  [1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[6 7 8 9]
[4 6 8]


In [ ]:
# omitting case -> when we can't provide the idx the it's automatically calcutate by using defautl value 

# access
print(arr1[:]) # start_idx = 0  ; end_idx = len(arr1) ; step = 1 

print(arr1[2::2]) # start_idx = 2; end_idx = len(arr1); steps = 2

print(arr1[:5:]) # start_idx = 0 : end_idx = 5-1 ; step = 1


[1 2 3 4 5 6 7 8 9]
[3 5 7 9]
[1 2 3 4 5]


#### Slicing for 2-d array
- syntax for 2-d:
    
    - arr_name[start_idx_row: end_idx_row: steps_row ,start_idx_col: end_idx_col: steps_col]

        - start_idx_row = 0 (default)
        - end_idx_row = total_row [default]
        - steps_row = 1 (default)

        - start_idx_col = 0 (default)
        - end_idx_col = total_col [default]
        - steps_col = 1 (default)

- remember that: 
    - end_idx is not include (exclusive)

    - ndarray follow 0-base indexing.


In [ ]:
arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 94, 98, 99]
])

print("Original Array: \n", arr2)


print("After slicing..")
# access
print(arr2[0:2,1:3])  # start_row_idx = 0 ; end_row_idx = 2-1; step = 1
                      # start_col_idx = 1 ; end_con_idx = 3-1 step = 1


Original Array: 
 [[10 20 30 40]
 [50 60 70 80]
 [90 94 98 99]]
After slicing..
[[20 30]
 [60 70]]


In [ ]:
# access only rows and columns


# acces only row
print("Original Array: \n", arr2)

print("After slicing specific row")

print(arr2[1:3,])  # start_row_idx = 1 ; end_row_idx = 3-1 ; step = 1
                    # start_col_idx = 0 ; end_con_idx = 4-1 step = 1 (select all columns)


# access only column
print("After slicing specific column")

print(arr2[::,:3])
                    # start_row_idx = 0 ; end_row_idx = all ; step = 1 (select all rows)
                    # start_col_idx = 0 ; end_con_idx = 3-1 step = 1 

print("After slicing ")
print(arr2[:, :])
                    # start_row_idx = 0 ; end_row_idx = all ; step = 1 (select all rows)
                    # start_col_idx = 0 ; end_con_idx = all ; step = 1 


Original Array: 
 [[10 20 30 40]
 [50 60 70 80]
 [90 94 98 99]]
After slicing specific row
[[50 60 70 80]
 [90 94 98 99]]
After slicing specific column
[[10 20 30]
 [50 60 70]
 [90 94 98]]
After slicing 
[[10 20 30 40]
 [50 60 70 80]
 [90 94 98 99]]


In [ ]:
# access with steps size

arr2 = np.arange(10,34,2).reshape(3,4)

print("Original array:\n",arr2)


print("\nSlicing with step size: ")
print(arr2[::2, ::2])

print("\nSlicing with step size: ")
print(arr2[::3, ::3])

print("\nSlicing with step size: ")
print(arr2[::3, 1::3])




Original array:
 [[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Slicing with step size: 
[[10 14]
 [26 30]]

Slicing with step size: 
[[10 16]]

Slicing with step size: 
[[12]]


In [ ]:
# what happen?
'''   
Original array:
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32] 


print("\nSlicing with step size: ")
print(arr2[::3, 1::3])

Step_01: for rows

    start_idx_row = 0  =>  [10 12 14 16]

    end_idx_row = len(arr) => 2

    step = 3

    
Step_02: for columns

    start_idx_col = 1  =>  [ 12 ]
                           [ 20 ]
                           [ 28 ] 

    end_idx_col = len(arr) => 3

    step = 3   => [ 12 ]

'''

In [91]:
# 2-d array: modify the elmeent using slicing 
arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 94, 98, 99]
])

print("Original array:\n",arr2)


print("\nSlicing with modification: ")

arr2[0:3:1, 0:4:1] = 100  # here all element is replace with 100
# arr2[::, ::] = 200

print(arr2)




Original array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 94 98 99]]

Slicing with modification: 
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
# 2-d array: modify the elmeent using slicing 
arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 94, 98, 99]
])
print("Original array:\n",arr2)


print("\nSlicing with modification specific rows and columms: ")

# arr2[1:3,:3] = 500
# print(arr2)


# arr2[1:, 1:] = 600

# print(arr2)


# arr2[:2, 1:3] = 200
# print(arr2)

arr2[::2,::3] = 100
print(arr2)



Original array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 94 98 99]]

Slicing with modification specific rows and columms: 
[[100  20  30 100]
 [ 50  60  70  80]
 [100  94  98 100]]


In [99]:
# specific row modify using slicing

arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 94, 98, 99]
])
print("Original array:\n",arr2)


print("\nSlicing with modification specific rows: ")

# arr2[0:1,::] = 100
# print(arr2)


arr2[0:1,::] = [100, 200, 300, 400]
print(arr2)



Original array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 94 98 99]]

Slicing with modification specific rows: 
[[100 200 300 400]
 [ 50  60  70  80]
 [ 90  94  98  99]]


In [103]:
# specific row delete using slicing
# np.delete(array, idx, axis)
# axis = 0 : row
# axis = 1 : column

arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 94, 98, 99]
])
print("Original array:\n",arr2)


print("\nSlicing with delete specific column: ")

new_arr = np.delete(arr2,2,axis=1)
print(new_arr)


# print("\nSlicing with delete specific row: ")

# new_arr = np.delete(arr2,2,axis=0)
# print(new_arr)





Original array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 94 98 99]]

Slicing with delete specific column: 
[[10 20 40]
 [50 60 80]
 [90 94 99]]


### 4. .view() Method

- Shallow Copy the main array.

- Changing data affects both.

- share data but not the object

In [ ]:
# for arrary slicing is similar to .view() method

arr = np.array([1,2,3,4,5,6,7,8,9])

sub_arr = arr[1:6]

print("Main Array: ", arr)
print("Sub Array: ", sub_arr)

# change in subarray
sub_arr[1] = 100
sub_arr[4] = 500

print("\nAfter modifying subArray: \n")
print("Main Array: ", arr)
print("Sub Array: ", sub_arr)


# NOTE: here Change the elements in both array

Main Array:  [1 2 3 4 5 6 7 8 9]
Sub Array:  [2 3 4 5 6]

After modifying subArray: 

Main Array:  [  1   2 100   4   5 500   7   8   9]
Sub Array:  [  2 100   4   5 500]


In [114]:
# Now use .view() method
arr = np.array([1,2,3,4,5,6,7,8,9])


# copy using .view()
copy_arr = arr.view()

print("Main Array: ", arr)
print("copy_arr Array: ", copy_arr) 


# modify the copy array
copy_arr[4] = 400
copy_arr[0] = 1010


print("\nAfter modify in copy array: ")

print("Main Array: ", arr)
print("copy_arr Array: ", copy_arr) 


Main Array:  [1 2 3 4 5 6 7 8 9]
copy_arr Array:  [1 2 3 4 5 6 7 8 9]

After modify in copy array: 
Main Array:  [1010    2    3    4  400    6    7    8    9]
copy_arr Array:  [1010    2    3    4  400    6    7    8    9]


### 5. .copy() Method

- Deep Copy the main array

- Changes in one do not affect the other

In [ ]:
# arr.copy() 

arr = np.array([1,2,3,4,5,6,7,8,9])

# deep copy

deep_copy = arr.copy()

print("Main Array: ", arr)
print("copy_arr Array: ", copy_arr) 

# modify the deep copy array

deep_copy[0] = 100
deep_copy[3] = 300



print("\nAfter modify in copy array: ")

print("Main Array: ", arr)
print("copy_arr Array: ", deep_copy) 


# NOTE: only modify the deep copy array not main array

Main Array:  [1 2 3 4 5 6 7 8 9]
copy_arr Array:  [1010    2    3    4  400    6    7    8    9]

After modify in copy array: 
Main Array:  [1 2 3 4 5 6 7 8 9]
copy_arr Array:  [100   2   3 300   5   6   7   8   9]
