## Topic: ndarray copy and Advance Indexing


### OUTCOMES

- 1. Fancy Indexing

- 2. Boolean Indexing

- 3. np.where()

- 4. np.any()

- 5. np.all()




### 1. Fancy Indexing


- To access and modify the specific elements in a array in non-sequence way.

- syntax for 1-d:
    - arr_name[[indices]]

In [2]:
import numpy as np

In [ ]:
# Fancy indexing for 1-d array

arr1 = np.arange(10,20)
print("Original Array: ",arr1)

# to access specific element
print("\nAccess specific idxs element: ", arr1[[5,3,2]])  # 1,2,3-> idx


idxs = [6,2,7]

print("\nAccess specific idxs element: ", arr1[idxs])

Original Array:  [10 11 12 13 14 15 16 17 18 19]

Access specific element:  [15 13 12]

Access specific element:  [16 12 17]


In [19]:
# fancy index for 2-d:
# syntax: arr_name[[row_idxs][col_idxs]]

arr2 = np.arange(1,21).reshape(4,5)
print("Original Array: \n",arr2)

# only specific rows and columns

rows = [3,0]
cols = [4,2]

print("\nSelect specific rows and columns: ")

print(arr2[rows,cols])



Original Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Select specific rows and columns: 
[20  3]


In [ ]:
# Explain
'''
Original Array: 

     columns
   0  1  2  3  4  
   .  .  .  .  . 
   v  v  v  v  v
 [ 1  2  3  4  5]  <-- 0  
 [ 6  7  8  9 10]  <-- 1   rows
 [11 12 13 14 15]  <-- 2
 [16 17 18 19 20]  <-- 3

print(arr2[rows,cols])
rows = [3,0]
cols = [4,2]

Step_01 : for row
    rows = [3,0] =>   [16 17 18 19 20]  <-- 3
                      [ 1  2  3  4  5]  <-- 0  

Step_02 : for column
    cols = [4,2] =>         2      4  
                            .      . 
                            v      v
                        [   3      5 ]  <-- 0  
                        [   8     10 ]  
                        [   13    15 ]
                        [   18    20 ]  <-- 3
Step_03 : for column
                  next:
                           (2nd)  (1st)
                            2      4
                            v      v
                        [   3      5 ]  <-- 0 (2nd)
                        [   18    20 ]  <-- 3 (1st)

     here,
     -  3,4 = 20
     -  0,2 = 3


output: [20, 3]
          
'''

In [ ]:
# only row access

print("Original Array: \n",arr2)

row = [3,0,2] 

print("\n only rows: ")
print(arr2[row])

Original Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 only rows: 
[[16 17 18 19 20]
 [ 1  2  3  4  5]
 [11 12 13 14 15]]


In [27]:
# only column access

print("Original Array: \n",arr2)

cols = [3,0,2] 

print("\n only col: ")
print(arr2[:, cols])

Original Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 only col: 
[[ 4  1  3]
 [ 9  6  8]
 [14 11 13]
 [19 16 18]]


In [ ]:
# modify specific element
# syntax: arr[[rows_idxs], [colns_idx]]

arr2 = np.arange(20, 40).reshape(4,5)

print("Original array: \n", arr2)

# To hightlight spefice element in ndarray

rows = [2,3,1]
cols = [1,3,2]

arr2[rows,cols] = 1000

print("Hightlight: \n", arr2)


Original array: 
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
Hightlight: 
 [[  20   21   22   23   24]
 [  25   26 1000   28   29]
 [  30 1000   32   33   34]
 [  35   36   37 1000   39]]


In [75]:
# Example : 1-d array modify using fancy idx

array1 = np.array([3, 2, 6, 1, 8, 5, 7, 4])


indices = [1, 3, 6]

new_values = [10, 20, 30]


array1[indices] = new_values

print(array1)

# Output: [ 3 10  6 20  8  5 30  4]

[ 3 10  6 20  8  5 30  4]


In [63]:
# specific rows modify

arr2 = np.arange(1,13).reshape(3,4)

print("Original array: \n", arr2)

# modify row

rows = [1,2]

arr2[rows,:] = 500

print("Modify rows: \n", arr2)




Original array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Modify rows: 
 [[  1   2   3   4]
 [500 500 500 500]
 [500 500 500 500]]


In [ ]:
# specific column modify

arr2 = np.arange(50,100).reshape(5,10)

print("Original array: \n", arr2)

# specific column update

cols = [2,5,8]

arr2[:,cols] = 1000

print("After modify the column: \n", arr2)

Original array: 
 [[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
After modify the column: 
 [[  50   51 1000   53   54 1000   56   57 1000   59]
 [  60   61 1000   63   64 1000   66   67 1000   69]
 [  70   71 1000   73   74 1000   76   77 1000   79]
 [  80   81 1000   83   84 1000   86   87 1000   89]
 [  90   91 1000   93   94 1000   96   97 1000   99]]


### 2. Boolean Indexing

- To filter and modity elements of an array based on condition

- return a new array

- syntax:
    - filter_array = array(codition)

In [ ]:
# 1-d array: Boolean Indexing

arr1 = np.arange(5,30,5)

print(arr1)

# filter array elements which are greater than 15

result = arr1[arr1 > 15]

# print(result)

res1 = arr1[(arr1 >= 10) & (arr1 < 20)]

# print(res1)


print(arr1[arr1 != 15])


[ 5 10 15 20 25]
[ 5 10 20 25]


In [ ]:
# Boolean indexing in 2-d array

arr2 = np.arange(12).reshape(4,3)

print("OR array: \n", arr2)

# to see the less than 5
res = arr2[arr2 < 5]
print("Less than five: \n",res)
print("Dimension: ", res.ndim)

OR array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Less than five: 
 [0 1 2 3 4]
Dimension:  1


In [88]:
# modifying array element using boolean idx

# modify 0 to 100 

arr2[arr2 == 0] = 100
print(arr2)




[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]



### 3. np.where()

- np.where can be used for conditional modifications, similar to if-else.

- syntax:
    np.where(condition, True_Result, False_Result)

In [ ]:
# Example:

arr = np.array([1,2,3,4,5,6,7,8,9])

new_arr = np.where(arr < 5 , 0, -1)  

print(new_arr)

new_arr = np.where(arr < 5 , 0, arr)
print(new_arr)




[ 0  0  0  0 -1 -1 -1 -1 -1]
[0 0 0 0 5 6 7 8 9]


### 4. np.any()

- np.any: Checks if any element along an axis satisfies a condition.

- syntax:
    - 

### 5. np.all()



- np.all: Checks if all elements along an axis satisfy a condition.

### 6. iteration over ndarray


In [2]:
import numpy as np

In [8]:
arr = np.array([
    [10, 20, 30],
    [5, 40, 50 ] 
     ])

# basic way

for i in arr:  # print rows way
    print(i)


# for each items
for i in arr:
    for j in i:
        print(j)


# np.nditer(arr) method
print("\nAccess each item using nditer")
for i in np.nditer(arr):
    print(i)


[10 20 30]
[ 5 40 50]
10
20
30
5
40
50

Access each item using nditer
10
20
30
5
40
50


In [123]:
### Practices 

In [ ]:
""" 

Practices for boolean indexing:
--------------------------------
 Features : id  | age  | salary   | year of Experience| 

dataset = (
    [101, 25, 60000, 4],
    [102, 24, 65000, 7], 
    [103, 35, 80000, 10],
    [104, 20, 20000, Nan],
    [105, 45, 45000, 3],
    [10, 55, 55000, 8],
    [107, Nan,35000, 6],
    [108, 25, 60000, Nan]
)

TasK_01 : Extract rows where Salary > 60000

Task_02 : Removing Outliers (Remove values less than 100 in id column )

Task_03: Highlight the Hight salary 

Task_04: Remove Missing Data (Replace Nan to 0)
"""

In [113]:
dataset = np.array([
    [101, 25, 60000, 4],
    [102, 24, 65000, 7], 
    [103, 35, 80000, 10],
    [104, 20, 20000, np.nan],
    [105, 45, 45000, 3],
    [10, 55, 55000, 8],
    [107, np.nan,35000, 6],
    [108, 25, 60000, np.nan]]
)

# print(dataset)
# print("Element tyPe: ", dataset.dtype)
# print(dataset.ndim)
print("shape: ", dataset.shape)



shape:  (8, 4)


In [ ]:
# TasK_01 : Extract rows where Salary > 60000


# cols = [2]
# print(dataset[:, cols])

greater_value = dataset[dataset > 60000]

print("Salary is greater then 60000: ",greater_value)


Salary is greater then 60000:  [65000. 80000.]


In [122]:
# Task_02 : Removing Outliers (Remove values less than 100 in id column )


# access or see the id column
# print(dataset[:,0])

# remove
clear = dataset[dataset[:,0] > 100]

# print(clear)
print(dataset)


print("Shape: ", dataset.shape)

[[1.01e+02 2.50e+01 6.00e+04 4.00e+00]
 [1.02e+02 2.40e+01 6.50e+04 7.00e+00]
 [1.03e+02 3.50e+01 8.00e+04 1.00e+01]
 [1.04e+02 2.00e+01 2.00e+04      nan]
 [1.05e+02 4.50e+01 4.50e+04 3.00e+00]
 [1.00e+01 5.50e+01 5.50e+04 8.00e+00]
 [1.07e+02      nan 3.50e+04 6.00e+00]
 [1.08e+02 2.50e+01 6.00e+04      nan]]
Shape:  (8, 4)


# Dataset: Rows represent [Age, Salary, Bonus]
data = np.array([
    [25, 50000, 5000],  
    [30, 60000, 6000],   
    [35, 70000, 7000]])   

# task_1: Update Salary for the first two employees
# task_2: Replace all salaries below 60000 with the minimum threshold of 60000.
# taks_03: highlight Employee who Salary below 60000 .  

In [ ]:
# slove Task_01: Update Salary for the first two employees

# Dataset: Rows represent [Age, Salary, Bonus]
data = np.array([
    [25, 50000, 5000],  
    [30, 60000, 6000],   
    [35, 70000, 7000]])   

print(f"Original Data : \n{data}")
print(f"Original Salary : \n{data[:,1]}")


# update slaray first two
salary_row = [0,1]
salary_col = [1,1]

data[salary_row, salary_col] = [55000,65000]

print("\nAfter update: \n", data)


In [ ]:
# Task_2: Replace all salaries below 60000 with the minimum threshold of 60000.
data = np.array([
    [25, 50000, 5000],  
    [30, 60000, 6000],   
    [35, 70000, 7000]])   

print(data)

print("salary column: ", data[:,1])

print("salary column: \n", data[data[:,1]>60000])


