## Topic: Numpy Array Manipulation_1

### OUTCOMES
- 1. Reshape
    - arr.reshape(new_size)

- 2. Convert array 
    - arr.flattern()
    - np.ravel(arr,order= "F")

- 3. Concatenation
    - np.concatenate(arr1,arr2)


### 1. Reshape

- Changing the structure of an array without changing it's data.

- use reshape() function

- syntax of reshape():
    - arr_name.reshape(new_size)

In [1]:
import numpy as np

In [4]:
# Example: reshape(new_shape)
# - change the original shape

# convert 1-d array to 2-d array
arr1 = np.array([1, 2, 3, 4, 5, 6, 7,8, 9])

print("Original array: ", arr1)
print("Shape: ", arr1.shape)
print("Dimension: ", arr1.ndim)


# convert 1-d to 2-d

arr2 = arr1.reshape(3,3)

print("Reshape or new array:\n", arr2)
print("Shape: ", arr2.shape)
print("Dimension: ", arr2.ndim)

Original array:  [1 2 3 4 5 6 7 8 9]
Shape:  (9,)
Dimension:  1
Reshape or new array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Dimension:  2


In [5]:
# if we try....

arr_error = arr1.reshape(2,3)
print(arr_error)


# NOTE
# - before and after reshaping the total numbers of elements are same.

# After reshape if we can't get the same numbers of elements the it will generate error.


ValueError: cannot reshape array of size 9 into shape (2,3)

In [64]:
# using (-1) Reshape

arr1 = np.array([1, 2, 3, 4, 5, 6, 7,8, 9])


arr2 = arr1.reshape(3,-1)  # -1 means automatical calculate the column numbers
                           
print(arr2)

# -1 : must be one parameter either row or column

arr = arr1.reshape(-1,3)
print("Auto detect: \n", arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Auto detect: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Reshape 2-d to 1-d

arr2 = np.random.randint(1,20, size = (4,3))

print("2-D array: \n", arr2)

print("Shape: ", arr2.shape)

# reshape 1d
arr1 = arr2.reshape(12)

print("1-d: \n", arr1)
print("Shape: ", arr1.shape)


2-D array: 
 [[ 8 10  2]
 [16  6  4]
 [ 9 12 12]
 [15 13 11]]
Shape:  (4, 3)
1-d: 
 [ 8 10  2 16  6  4  9 12 12 15 13 11]
Shape:  (12,)


### 2. Convert array (2-d to 1-d)

In [14]:
# convert one dimension to another dimension

# 2-d to 1-d using -> arr.flatten()

arr2 = np.random.randint(1,10, size = (3,4))

print("2-d Array: \n", arr2)

# now convert 2-d to 1-d

flattern_1d_array = arr2.flatten()

print("1-d Array: \n", flattern_1d_array)


# NOTE - > arr.flatten(): convert 2-d to 1-d array in rows wise.

2-d Array: 
 [[8 2 4 5]
 [5 8 4 8]
 [1 1 7 7]]
1-d Array: 
 [8 2 4 5 5 8 4 8 1 1 7 7]


In [ ]:
# method-02: np.ravel(arr,order = "F")
# order : "F" means conver 2-d to 1-d in the form columns wise 
# order : "C" means conver 2-d to 1-d in the form rows wise (default)


arr2 = np.arange(1,21).reshape(5,4)

print("2-d Array: \n", arr2)

# convert 2-d to 1-d in rows wise (default)

row_wise_1d = np.ravel(arr2,order = "C")
# row_wise_1d = np.ravel(arr2)  # default count row-wise

print("1-d Array Row wise: \n", row_wise_1d)


# convert 2-d to 1-d in column wise 
col_wise_1d  = np.ravel(arr2, order="F")

print("1-d Array Column wise: \n", col_wise_1d)


2-d Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
1-d Array Row wise: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1-d Array Column wise: 
 [ 1  5  9 13 17  2  6 10 14 18  3  7 11 15 19  4  8 12 16 20]


### 3. Concatenation

- Add (concatenate) two or more ndarray in Elements wise 

- Two method:
    - 1. rows-wise concatenate
    - 2. column-wise concatenate

- Condition for concatenate
    - To concatenate arrays, both must have the same number of dimensions.
    - for rows-wise: numbers of columns are same both array.
    - for coln-wise: number of rows are same both array.

- syntax of np.concatenate((arr1,arr2), axis = 0)
    - first argument two array in tuple format
    - 1 = rows wise concatenate
    - 0 = column wise concatenate

In [30]:
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([15, 25, 35, 45, 55])


# 1. rows-wise concatenate
print("Shape: ", arr1.shape)  #  here two array same shape (allow to concatenate in rows wise)
print("Shape: ", arr2.shape)


# concatenate : axis = 1 menas rows
con = np.concatenate((arr1,arr2), axis=0)

print("Arr1: \n", arr1)
print("Arr2: \n", arr2)

print("Row Con Array: \n", con)



Shape:  (5,)
Shape:  (5,)
Arr1: 
 [10 20 30 40 50]
Arr2: 
 [15 25 35 45 55]
Row Con Array: 
 [10 20 30 40 50 15 25 35 45 55]


In [31]:
# 2. column-wise concatenate
con_col = np.concatenate((arr1,arr2), axis=1)
print("Column Con Array: ", con_col)

# here both array are 1-d (vector) there is no columns 

AxisError: axis 1 is out of bounds for array of dimension 1

In [47]:
# Example: concatenation : vector and matrix

vector = np.array([10, 20, 30, 40, 50]).reshape(5,1)  # To concatenate arrays, both must have the same number of dimensions.

print("Shape of Vector: ", vector.shape)
print("vector: \n", vector)

matrix = np.random.randint(1,10, size=(5,3))
print("Shape of Matrix: ", matrix.shape)
print("Matrix: \n", matrix)

# concatenate

con_arr = np.concatenate((vector,matrix),axis=1)

print("Column Wise concatenate: \n", con_arr)

Shape of Vector:  (5, 1)
vector: 
 [[10]
 [20]
 [30]
 [40]
 [50]]
Shape of Matrix:  (5, 3)
Matrix: 
 [[4 7 6]
 [6 4 7]
 [3 6 4]
 [9 3 2]
 [7 2 1]]
Column Wise concatenate: 
 [[10  4  7  6]
 [20  6  4  7]
 [30  3  6  4]
 [40  9  3  2]
 [50  7  2  1]]


In [50]:
# Example : concatenates

arr1 = np.random.randint(10,30, size= (5,6))
arr2 = np.random.randint(40,60, size= (6,5))


print("Arr1 : \n", arr1)
print("Arr2 : \n", arr2)


# concate in rows wise 
print("Shape of arr1: ", arr1.shape)
print("Shape O arr2: ", arr2.shape)


# rows wise concatenate(axis = 1) | no. of columns are same of both array

con_row = np.concatenate((arr1,arr2), axis=0)

print(con_row)  # here no of column are not same both array

Arr1 : 
 [[27 26 14 22 29 18]
 [11 15 25 10 19 13]
 [19 22 13 19 16 27]
 [24 29 28 29 17 22]
 [25 29 24 21 26 23]]
Arr2 : 
 [[51 46 48 41 59]
 [44 54 42 55 49]
 [42 42 54 57 42]
 [51 50 52 57 43]
 [41 56 40 49 51]
 [54 49 50 55 41]]
Shape of arr1:  (5, 6)
Shape O arr2:  (6, 5)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 5

In [51]:
# rows wise concatenate(axis = 1) | no. of columns are same

con_col = np.concatenate((arr1,arr2), axis=1)

# ValueError: because here number of rows are not same both array

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 6

In [55]:
# Example where no.of column are same

arr1 = np.random.randint(1,10, size = (3,4))

print("Arr1: \n", arr1)
print("Shape: ", arr1.shape)



arr2 = np.random.randint(11,20, size = (2,4))
print("Arr1: \n", arr2)
print("Shape: ", arr2.shape)


# only concatenate in column-wise

con_rows = np.concatenate((arr1,arr2), axis=0)

print("Row Wise array: \n", con_rows)


Arr1: 
 [[8 7 9 8]
 [8 8 5 8]
 [7 8 4 1]]
Shape:  (3, 4)
Arr1: 
 [[19 14 17 16]
 [18 12 15 15]]
Shape:  (2, 4)
Row Wise array: 
 [[ 8  7  9  8]
 [ 8  8  5  8]
 [ 7  8  4  1]
 [19 14 17 16]
 [18 12 15 15]]


In [59]:
# Example where no.of rows are same

arr1 = np.random.randint(1,10, size = (3,2))

print("Arr1: \n", arr1)
print("Shape: ", arr1.shape)



arr2 = np.random.randint(11,20, size = (3,4))
print("Arr1: \n", arr2)
print("Shape: ", arr2.shape)


# only concatenate in row-wise

con_rows = np.concatenate((arr1,arr2), axis=1)

print("Row Wise array: \n", con_rows)


Arr1: 
 [[9 4]
 [6 3]
 [3 5]]
Shape:  (3, 2)
Arr1: 
 [[17 17 19 11]
 [18 15 14 19]
 [17 14 18 12]]
Shape:  (3, 4)
Row Wise array: 
 [[ 9  4 17 17 19 11]
 [ 6  3 18 15 14 19]
 [ 3  5 17 14 18 12]]


In [62]:
# when row and column are same

arr1 = np.random.randint(1,10, size = (3,4))

print("Arr1: \n", arr1)
print("Shape: ", arr1.shape)



arr2 = np.random.randint(11,20, size = (3,4))
print("Arr1: \n", arr2)
print("Shape: ", arr2.shape)


# concatenate in row-wise

con_rows = np.concatenate((arr1,arr2), axis=1)

print("Row Wise array: \n", con_rows)


# concatenate in column wise
con_column = np.concatenate((arr1, arr2),axis= 0)
print("Column wise array: \n", con_column)




Arr1: 
 [[2 5 2 9]
 [9 9 1 3]
 [4 1 3 7]]
Shape:  (3, 4)
Arr1: 
 [[14 16 12 12]
 [14 18 14 16]
 [18 15 17 18]]
Shape:  (3, 4)
Row Wise array: 
 [[ 2  5  2  9 14 16 12 12]
 [ 9  9  1  3 14 18 14 16]
 [ 4  1  3  7 18 15 17 18]]
Column wise array: 
 [[ 2  5  2  9]
 [ 9  9  1  3]
 [ 4  1  3  7]
 [14 16 12 12]
 [14 18 14 16]
 [18 15 17 18]]
