## Topic: Numpy Array Manipulation_2

### OUTCOMES

- 1. Transpose
    - np.transpose(arr)
    - arr.T

- 2. Split
    - np.split(arr,split_size,axis=0)
    - np.array_split(arr,split_size,axis=0)

- 3. Differnce between Transpose and Split

### 1. Transpose

- Swap it's rows with it's column (vice-versa)

- functions : 
    - arr.T
    - transpose(arr)

- Ex: 
    - A.shape(m,n)
    - A.T shape(n,m)


In [1]:
import numpy as np

In [ ]:
# Example of Transpose Matrix

# 1-d : 
arr1 = np.array([10, 20, 30, 40, 50, 60])

print("Original Array: ", arr1)
print("Shape: ", arr1.shape)
print("Dimension: ", arr1.ndim)

# Trnaspose
tranpose_arr1 = arr1.T

print("\nTranspose of arr1: \n", tranpose_arr1) 
print("Shape: ", tranpose_arr1.shape)
print("Dimension: ", tranpose_arr1.ndim)

Original Array:  [10 20 30 40 50 60]
Shape:  (6,)
Dimension:  1

Transpose of arr1: 
 [10 20 30 40 50 60]
Shape:  (6,)
Dimension:  1


In [53]:
# Example Transpose of 2-d

arr2 = np.random.randint(5,20, size=(5,3))

print("Arr2: \n", arr2)
print("Dimension: ",arr2.ndim)
print("Shape: ", arr2.shape)


# Transpose
tp_arr2 = arr2.T

print("\nTranspose Arr2: \n", tp_arr2)
print("Dimension: ",tp_arr2.ndim)
print("Shape: ", tp_arr2.shape)  # change shape: 3,5


Arr2: 
 [[19  7  5]
 [ 9 13  9]
 [ 6  8  8]
 [11 15 17]
 [19 18  9]]
Dimension:  2
Shape:  (5, 3)

Transpose Arr2: 
 [[19  9  6 11 19]
 [ 7 13  8 15 18]
 [ 5  9  8 17  9]]
Dimension:  2
Shape:  (3, 5)


In [54]:
# Example Transpose of 2-d : -> using np.transpose(arr)

arr2 = np.random.randint(5,20, size=(4,3))

print("Arr2: \n", arr2)
print("Dimension: ",arr2.ndim)
print("Shape: ", arr2.shape)


# Transpose
tp_arr2 = np.transpose(arr2)

print("\nTranspose Arr2: \n", tp_arr2)
print("Dimension: ",tp_arr2.ndim)
print("Shape: ", tp_arr2.shape)  # change shape: 3,5


Arr2: 
 [[17  9 18]
 [10  9  8]
 [10  6  7]
 [ 9  6  7]]
Dimension:  2
Shape:  (4, 3)

Transpose Arr2: 
 [[17 10 10  9]
 [ 9  9  6  6]
 [18  8  7  7]]
Dimension:  2
Shape:  (3, 4)


In [15]:
# for square matrix: 

arr1 = np.random.randint(10,20, size=(2,2))

print("Arr1: \n", arr1)
print("Shape: ", arr1.shape)


# transpose
square_tranpose = np.transpose(arr1)

print("square_tranpose: \n", square_tranpose)
print("square_tranpose: ", square_tranpose.shape)


Arr1: 
 [[17 19]
 [15 13]]
Shape:  (2, 2)
square_tranpose: 
 [[17 15]
 [19 13]]
square_tranpose:  (2, 2)


### 2. Split

- refers to dividing a large array into multiple smaller sub array.

- Two way:
    - 1. np.split(arr,section,axis=0)

    - 2. np.array_split(arr,split_size,axis=0)

#### 1. np.split(arr,section,axis=0)

- np.split(arr,section,axis=0)
- section = how many part to split
- axis    => rows or columns wise split


In [ ]:
#  Example

# split with row # split into row wise
arr1 = np.random.randint(1,10, size=(9,))

print("Array1: \n", arr1)
print("Shape: ", arr1.shape)
print("Dimension: ", arr1.ndim)


# split into row wise (axis = 0)
split_arr = np.split(arr1,3,axis = 0)

print(split_arr)


Array1: 
 [6 6 6 9 3 5 8 4 2]
Shape:  (9,)
Dimension:  1
[array([6, 6, 6], dtype=int32), array([9, 3, 5], dtype=int32), array([8, 4, 2], dtype=int32)]


In [ ]:
# split with row 

# 1-d array
arr1 = np.random.randint(1,10, size=(10,))

print("Array1: \n", arr1)
print("Shape: ", arr1.shape)
print("Dimension: ", arr1.ndim)


# split into row wise (axis = 0)
split_arr = np.split(arr1,3,axis = 0)

print(split_arr)

# NOTE -> np.split() function split the elements into equal division otherwise ValueError

Array1: 
 [1 9 5 4 7 4 3 7 1 8]
Shape:  (10,)
Dimension:  1


ValueError: array split does not result in an equal division

In [ ]:
# split 2-d array - row wise

arr2 = np.random.randint(1,15, size=(4,5))

print("Array1: \n", arr2)
print("Shape: ", arr2.shape)


# split into row wise (axis = 0)
split_arr = np.split(arr2,4,axis = 0)

print(split_arr)

# here 20 elements can divide into 4 equal division (in rows wise)

Array1: 
 [[ 3  4 10  6  7]
 [ 9 13  8 14  7]
 [11  3  4  1 12]
 [12  6  8  6 11]]
Shape:  (4, 5)
[array([[ 3,  4, 10,  6,  7]], dtype=int32), array([[ 9, 13,  8, 14,  7]], dtype=int32), array([[11,  3,  4,  1, 12]], dtype=int32), array([[12,  6,  8,  6, 11]], dtype=int32)]


In [ ]:
# split 2-d array -> column wise

arr2 = np.random.randint(1,15, size=(4,5))

print("Array1: \n", arr2)
print("Shape: ", arr2.shape)


# split into column wise (axis = 1)
split_arr = np.split(arr2,4,axis = 1)

print(split_arr)

# here 20 elements can not divide into 4 equal division in columns wise

Array1: 
 [[ 5  8 11  2 14]
 [ 4 10  5  4  5]
 [ 7  5 10 12 14]
 [14  6 10  6  1]]
Shape:  (4, 5)


ValueError: array split does not result in an equal division

In [ ]:
# np.split(arr,section,axis=0) for 2-d array


# split with row # split into row wise
arr2 = np.random.randint(1,15, size=(5,2))

print("Array1: \n", arr2)
print("Shape: ", arr2.shape)


# split into row wise (axis = 0)
split_arr = np.split(arr2,3,axis = 0)

print(split_arr)


# # NOTE -> np.split() function split the elements into equal division other wise ValueError
# here shape(5,2) mesns total elements are 10
# 10 elements can't divide into 3 equal division 

Array1: 
 [[10  6]
 [12  4]
 [ 7 11]
 [13  2]
 [10  6]]
Shape:  (5, 2)


ValueError: array split does not result in an equal division

In [42]:
# np.split(arr,split_size,axis=0) use when we to equal divison

arr2 = np.random.randint(5,50, size=(4,6))

print("Arr2: \n", arr2)

# row-wise equal divion
split_row_equal = np.split(arr2,2,axis=0)

print("Split array: \n", split_row_equal)


# column wise split
split_col = np.split(arr2,3,axis=1)
print("Column split: \n", split_col)



Arr2: 
 [[17 41 22 46 14 19]
 [22 11  9 39  7 33]
 [16 27 10 10 32 30]
 [ 5 13 30 46  9 26]]
Split array: 
 [array([[17, 41, 22, 46, 14, 19],
       [22, 11,  9, 39,  7, 33]], dtype=int32), array([[16, 27, 10, 10, 32, 30],
       [ 5, 13, 30, 46,  9, 26]], dtype=int32)]
Column split: 
 [array([[17, 41],
       [22, 11],
       [16, 27],
       [ 5, 13]], dtype=int32), array([[22, 46],
       [ 9, 39],
       [10, 10],
       [30, 46]], dtype=int32), array([[14, 19],
       [ 7, 33],
       [32, 30],
       [ 9, 26]], dtype=int32)]


#### 2. np.array_split(arr,split_size,axis=0)

- unequal split of the element into .

- syntax: np.split_array(arr,split_size,axis=0)

    - axis = 0 means rows split
    - axis = 1 mens columns split


In [ ]:
# np.array_split(arr,split_size, axis=0)

# 1-d
arr1 = np.random.randint(1,10, size=(10,))

print("Arr1: \n", arr1)
print("Shape: ", arr1.shape)

# unequal split into row wise

split_row = np.array_split(arr1,4,axis=0)

print("Split Array: \n", split_row)



# first split into equaly way if elemets are remain then again split first to last


Arr1: 
 [7 4 1 1 7 6 5 8 7 7]
Shape:  (10,)
Split Array: 
 [array([7, 4, 1], dtype=int32), array([1, 7, 6], dtype=int32), array([5, 8], dtype=int32), array([7, 7], dtype=int32)]


In [51]:
# Example: np.array_split(arr, split_size, axix = 1)

arr2 = np.random.randint(1,20, size = (4,5))

print("Array: \n", arr2)

# split into column wise

col_split = np.array_split(arr2, 3, axis = 1)

print("Column Split: \n", col_split)




Array: 
 [[10  1  9 15  6]
 [16 16 10 18 11]
 [ 9  9  2 11  4]
 [10 17  3 16  4]]
Column Split: 
 [array([[10,  1],
       [16, 16],
       [ 9,  9],
       [10, 17]], dtype=int32), array([[ 9, 15],
       [10, 18],
       [ 2, 11],
       [ 3, 16]], dtype=int32), array([[ 6],
       [11],
       [ 4],
       [ 4]], dtype=int32)]


### 3. Differnce between Transpose and Split