## Topic: ndarray Arithemetic Operators and Mathematical function

### OUTCOMES

- 1. Basic Mathematical Operation

- 2. Trigonometic Opertion

- 3. Conversion (degree to radian and vice-versa)

- 4. log 

- 5. Squrt Calculation

- 6. Cumlative sumation

In [2]:
import numpy as np

### 1. Basic Mathematical Operation

- Rules:
    - Dimension of two array must be same
    - size must be same

In [ ]:
# addition (elements) waise two ndarray 

arr1 = np.random.randint(1,15, size= (4,3))

print("Arr1: \n", arr1)

arr2 = np.random.randint(1,20, size=(4,3))

print("Arr2: \n", arr2)


# addition operation
add = arr1 + arr2

print("Addition: \n", add)


# other way

add_other = np.add(arr1,arr2)
print("\nAnother Addition: \n", add_other)


Arr1: 
 [[10 13 10]
 [12  4  6]
 [ 1  5  3]
 [ 3 14  3]]
Arr2: 
 [[18 12 11]
 [ 8 14 15]
 [ 7 16  2]
 [18  5 17]]
Addition: 
 [[28 25 21]
 [20 18 21]
 [ 8 21  5]
 [21 19 20]]

Another Addition: 
 [[28 25 21]
 [20 18 21]
 [ 8 21  5]
 [21 19 20]]


In [15]:
# Substruction
sub = arr1 - arr2   # Element ways sub


print("Arr1: \n", arr1)

arr2 = np.random.randint(1,20, size=(4,3))

print("Arr2: \n", arr2)

print("substruction: \n", sub)




Arr1: 
 [[10 13 10]
 [12  4  6]
 [ 1  5  3]
 [ 3 14  3]]
Arr2: 
 [[14 18 14]
 [19  5 18]
 [ 1  3 18]
 [16  6  6]]
substruction: 
 [[ -8  -3  -9]
 [ -2  -5 -11]
 [-13  -1  -7]
 [-15  -4  -7]]


In [16]:
# multiplication
mul = arr1 * arr2   # Element ways sub


print("Arr1: \n", arr1)

arr2 = np.random.randint(1,20, size=(4,3))

print("Arr2: \n", arr2)

print("substruction: \n", mul)



Arr1: 
 [[10 13 10]
 [12  4  6]
 [ 1  5  3]
 [ 3 14  3]]
Arr2: 
 [[12 12  8]
 [10 15  1]
 [ 8 16  9]
 [ 8  7  8]]
substruction: 
 [[140 234 140]
 [228  20 108]
 [  1  15  54]
 [ 48  84  18]]


In [17]:
# Division
div = arr1 / arr2   # Element ways sub


print("Arr1: \n", arr1)

arr2 = np.random.randint(1,20, size=(4,3))

print("Arr2: \n", arr2)

print("substruction: \n", div)



Arr1: 
 [[10 13 10]
 [12  4  6]
 [ 1  5  3]
 [ 3 14  3]]
Arr2: 
 [[12  8  6]
 [11 15  7]
 [19  4  9]
 [10  8 16]]
substruction: 
 [[0.83333333 1.08333333 1.25      ]
 [1.2        0.26666667 6.        ]
 [0.125      0.3125     0.33333333]
 [0.375      2.         0.375     ]]


### 2. Trigonometic Opertion

In [20]:
arr2 = np.random.randint(1,15, size = (4,8))

print("Arr2: \n", arr2)


# sin
sin_val = np.sin(arr2)

print("Arr2 sin values: \n", sin_val)

Arr2: 
 [[ 2  7  4 13 13 14  6 12]
 [13  3  2 10 14  7  6  1]
 [12  6 12  1  4 11 12 13]
 [ 8  4  4  3 13 10  1  4]]
Arr2 sin values: 
 [[ 0.90929743  0.6569866  -0.7568025   0.42016704  0.42016704  0.99060736
  -0.2794155  -0.53657292]
 [ 0.42016704  0.14112001  0.90929743 -0.54402111  0.99060736  0.6569866
  -0.2794155   0.84147098]
 [-0.53657292 -0.2794155  -0.53657292  0.84147098 -0.7568025  -0.99999021
  -0.53657292  0.42016704]
 [ 0.98935825 -0.7568025  -0.7568025   0.14112001  0.42016704 -0.54402111
   0.84147098 -0.7568025 ]]


In [22]:
# cos
cos_vals = np.cos(arr2)

print("Arr2 cos values: \n", cos_vals)

Arr2 cos values: 
 [[-0.41614684  0.75390225 -0.65364362  0.90744678  0.90744678  0.13673722
   0.96017029  0.84385396]
 [ 0.90744678 -0.9899925  -0.41614684 -0.83907153  0.13673722  0.75390225
   0.96017029  0.54030231]
 [ 0.84385396  0.96017029  0.84385396  0.54030231 -0.65364362  0.0044257
   0.84385396  0.90744678]
 [-0.14550003 -0.65364362 -0.65364362 -0.9899925   0.90744678 -0.83907153
   0.54030231 -0.65364362]]


In [21]:
# tan 
tan_vals = np.tan(arr2)

print("Arr2 tan values: \n", tan_vals)

Arr2 tan values: 
 [[-2.18503986e+00  8.71447983e-01  1.15782128e+00  4.63021133e-01
   4.63021133e-01  7.24460662e+00 -2.91006191e-01 -6.35859929e-01]
 [ 4.63021133e-01 -1.42546543e-01 -2.18503986e+00  6.48360827e-01
   7.24460662e+00  8.71447983e-01 -2.91006191e-01  1.55740772e+00]
 [-6.35859929e-01 -2.91006191e-01 -6.35859929e-01  1.55740772e+00
   1.15782128e+00 -2.25950846e+02 -6.35859929e-01  4.63021133e-01]
 [-6.79971146e+00  1.15782128e+00  1.15782128e+00 -1.42546543e-01
   4.63021133e-01  6.48360827e-01  1.55740772e+00  1.15782128e+00]]


### 3. Conversion (degree to radian and vice-versa)

In [28]:
# radian(default) to degree

arr2 = np.random.randint(1,25, size = (3,5))

print("Arr2: \n", arr2)


# red2deg
deg_vals = np.rad2deg(arr2)

print("Arr2 degree values: \n", deg_vals)



Arr2: 
 [[17 17 13 12  3]
 [ 8 20 10 22 17]
 [ 5 24 14 21 11]]
Arr2 degree values: 
 [[ 974.02825172  974.02825172  744.84513367  687.54935416  171.88733854]
 [ 458.3662361  1145.91559026  572.95779513 1260.50714929  974.02825172]
 [ 286.47889757 1375.09870831  802.14091318 1203.21136977  630.25357464]]


In [29]:
# degree to radian

arr2 = np.random.randint(1,25, size = (3,5))

print("Arr2: \n", arr2)


# deg2rad
rad_vals = np.deg2rad(arr2)

print("Arr2 degree values: \n", rad_vals)



Arr2: 
 [[ 6  4 17 19  9]
 [15 13 10 10 17]
 [10  8  3 21 23]]
Arr2 degree values: 
 [[0.10471976 0.06981317 0.29670597 0.33161256 0.15707963]
 [0.26179939 0.2268928  0.17453293 0.17453293 0.29670597]
 [0.17453293 0.13962634 0.05235988 0.36651914 0.40142573]]


### 4. log 

In [ ]:
# log 10 base 
arr1 = np.array([1,2,3,8,5])

base_10_log = np.log10(arr1)

print("Original Array: \n", arr1)
print("Log 10 base: \n", base_10_log)

[1 2 3 8 5]
[0.         0.30103    0.47712125 0.90308999 0.69897   ]


In [30]:
# log 2 base
two_base_log = np.log2(arr1)

print(two_base_log)

[0.         1.         1.5849625  3.         2.32192809]


### 5. Squrt Calculation

In [33]:
# squart root
arr1 = np.array([1,2,3,8,5])

sqrt_arr = np.sqrt(arr1)

print("Squar Root: \n", sqrt_arr)

Squar Root: 
 [1.         1.41421356 1.73205081 2.82842712 2.23606798]


### 6. Cumlative summation

In [36]:
# cumlative sum
arr1 = np.array([1,2,3,8,5])

cum_sum = np.cumsum(arr1)

print("Cumlative summation: \n", cum_sum)


Cumlative summation: 
 [ 1  3  6 14 19]
