### Topic: 4. Numpy Broadcasting

- performing arithmetic operations on arrays of different shapes or sizes.

- Rules
    - 2d column size and 1-d size same (for 1-d and 2d)  

In [2]:
import numpy as np

In [ ]:
# Example of broadcasting

arr = np.array([10, 20, 30, 40, 50, 60])

result = arr + 2

print("Arr: \n", arr)

print("Result: \n", result)

Arr: 
 [10 20 30 40 50 60]
Result: 
 [12 22 32 42 52 62]


In [ ]:
# Example: broadcasting 1-d and 2d

scalar = np.array([1,2,3])

matrix = np.array([
    [10, 20, 30],
    [15, 25, 35], 
    [40, 50, 60]
])

# result = matrix + scalar

result = scalar + matrix 


print(result)


[[11 22 33]
 [16 27 38]
 [41 52 63]]


In [ ]:
# Example: column broadcastin

arr1 = np.array([
    [10, 20, 30],
    [15, 25, 35] 
])

arr2 = np.array([
    [10],
    [20]
]    
)

result = arr1 + arr2

print(result)


[[20 30 40]
 [35 45 55]]


In [ ]:
# Error case
# when row or column shape don't match

arr1 = np.array([
    [10, 20, 30],
    [15, 25, 35] 
])

arr2 = np.array([
    [10, 20],
    [30, 40]
    
]    
)

result = arr1 + arr2

print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [20]:
# real Example
# Temperature conversion cel to far: (celsius * 9/5 + 32)

cel_temp = np.random.randint(15, 30, size= (3,4))

cel_temp = cel_temp.astype(np.float32)

print("celsius  temp: \n", cel_temp)


# conversion

far_temp = cel_temp * 9/5 + 32

print("Fahrenheit temp: \n", far_temp)



celsius  temp: 
 [[26. 23. 22. 20.]
 [26. 15. 23. 16.]
 [28. 28. 21. 17.]]
Fahrenheit temp: 
 [[78.8 73.4 71.6 68. ]
 [78.8 59.  73.4 60.8]
 [82.4 82.4 69.8 62.6]]
