## Topic: Sorting ndarray Elements

### OUTCOMES

- 1. Introductio of Sorting

    - Definition

    - Predifine method/function

    - Application/why need in ML?


- 2. Sorting Rules 
    - copy sort
    - In-place sort
    - Axis control

- 3. Sorting Indices
    - np.argsor

- 4. Decending sort

- 5. Practices with Real-life Examples

In [1]:
import numpy as np

### 1. Introductio of Sorting

- Definition
    - Sorting in NumPy means arranging array elements in ascending or descending order along a specified axis.

- Predifine method/function

    - 1. arr.sort()    -> function based (In-place sort)
    
    - 2. np.sort()   -> Method based (Copy sort)
    
    - 3. np.argsort()  -> indix based



- Application/why need in ML?
    - Get Top K-Selection (values)
    - Feature Ranking (Sort features by importance score)


### 2. Sorting Rules 

- Copy sort
    - np.arr() Return a 'new' sorted array

- In-place sort
    - arr.sort(): Sort the 'original' array in place.


- Axis control

    - Case_1: axis = 1 (sort rows wise)
        - Sorts each row independently, left to right(<<----).
        - eg: np.sort(arr, axis=1)

    
    - Case_2: axis = 0 (sort columns wise)
        - Sort each column Top to bottom.

    
    - Case_3: axis = 0 (Sort the Entire array)
        - flattern into 1-d array
        - eg: np.sort(arr, axis= None)


#### Copy sort -> np.sort(arr, axis=)

In [5]:
## 1-d: Copy sort

arr1 = np.random.randint(1,15, size=(10,))

print("Original Array: \n", arr1)

# copy sort: return a new sorted array

new_copy_arr = np.sort(arr1)

print("Copy sort: \n", new_copy_arr)

print("Original Array: \n", arr1)  # Not change 


# NOTE -> 1-d array don't exist axis 

Original Array: 
 [13 13  6  1 11 14  9  8  7 13]
Copy sort: 
 [ 1  6  7  8  9 11 13 13 13 14]
Original Array: 
 [13 13  6  1 11 14  9  8  7 13]


In [ ]:
## 2-d : copy sort :-> np.sort(arr, axix = 1)
# Case_01: sort into rows-wise

arr2 = np.random.randint(5,20, size = (5,6))

print("Original Array: \n", arr2)


# Apply copy sort

new_sort_arr = np.sort(arr2, axis = 1)

print("Sorted Array: \n", new_sort_arr)


print("Original Array: \n", arr2)


# NOTE -> copy sort can't change the main or original array

Original Array: 
 [[19 11 11  7  8 16]
 [19  8 12 13 18  7]
 [13  8  6  5 10  5]
 [12 15  8 13 19  8]
 [19 19 17 14  7 10]]
Sorted Array: 
 [[ 7  8 11 11 16 19]
 [ 7  8 12 13 18 19]
 [ 5  5  6  8 10 13]
 [ 8  8 12 13 15 19]
 [ 7 10 14 17 19 19]]
Original Array: 
 [[19 11 11  7  8 16]
 [19  8 12 13 18  7]
 [13  8  6  5 10  5]
 [12 15  8 13 19  8]
 [19 19 17 14  7 10]]


In [15]:
## 2-d : copy sort :-> np.sort(arr, axix = 0)
# Case_01: sort into column-wise

arr2 = np.random.randint(5,20, size = (5,4))

print("Original Array: \n", arr2)


# Apply copy sort

new_sort_arr = np.sort(arr2, axis = 0)

print("Sorted Array: \n", new_sort_arr)


print("Original Array: \n", arr2)


# NOTE -> copy sort can't change the main or original array

Original Array: 
 [[ 6 14 16  5]
 [ 6 16  6 15]
 [13  7 15 10]
 [13  8 16  6]
 [ 9  5 19 11]]
Sorted Array: 
 [[ 6  5  6  5]
 [ 6  7 15  6]
 [ 9  8 16 10]
 [13 14 16 11]
 [13 16 19 15]]
Original Array: 
 [[ 6 14 16  5]
 [ 6 16  6 15]
 [13  7 15 10]
 [13  8 16  6]
 [ 9  5 19 11]]


In [ ]:
## 2-d : copy sort :-> np.sort(arr, axix = None)
# Case_01: sort into elements wise and convert inot 1-d array

arr2 = np.random.randint(5,20, size = (8,8))

print("Original Array: \n", arr2)


# Apply copy sort

new_sort_arr = np.sort(arr2, axis = None)

print("Sorted Array: \n", new_sort_arr)


print("Original Array: \n", arr2)


# NOTE -> axis = None
    # sort and conver 1-d array

Original Array: 
 [[10  5 10 16 18  8  8 16]
 [14  6 11 14 15 14 14 11]
 [19 13 15 15  7  9 18 14]
 [13  8 18  8  5 11  8  5]
 [ 7 19 11  5 10 13  8 17]
 [ 6 10  8 19 19 15 19  5]
 [ 6 13 19 16 18  7 14 10]
 [11 19  5 19 14  8 18  6]]
Sorted Array: 
 [ 5  5  5  5  5  5  6  6  6  6  7  7  7  8  8  8  8  8  8  8  8  9 10 10
 10 10 10 11 11 11 11 11 13 13 13 13 14 14 14 14 14 14 14 15 15 15 15 16
 16 16 17 18 18 18 18 18 19 19 19 19 19 19 19 19]
Original Array: 
 [[10  5 10 16 18  8  8 16]
 [14  6 11 14 15 14 14 11]
 [19 13 15 15  7  9 18 14]
 [13  8 18  8  5 11  8  5]
 [ 7 19 11  5 10 13  8 17]
 [ 6 10  8 19 19 15 19  5]
 [ 6 13 19 16 18  7 14 10]
 [11 19  5 19 14  8 18  6]]


#### In-place sort (arr.sort())

In [ ]:
# 1-d: In-place sort

arr1 = np.random.randint(5,15, size = (12))

print("Orginal Array: \n", arr1)

# Apply in-place sort

arr1.sort()
# arr1 = arr1.sort()


print("Sorted Array: \n",arr1)


print("Orginal Array: \n", arr1)


# NOTE -> In-place sort: sorted the main or original array


Orginal Array: 
 [10 13 11 14 13  6  9 11  6 10 12 13]
Sorted Array: 
 [ 6  6  9 10 10 11 11 12 13 13 13 14]
Orginal Array: 
 [ 6  6  9 10 10 11 11 12 13 13 13 14]


In [28]:
## 2-d : copy sort :-> np.sort(arr, axix = None)


arr2 = np.random.randint(5,20, size = (4,5))

print("Original Array: \n", arr2)


# Apply in-place sort

arr2.sort()


print("Original Array: \n", arr2)


# NOTE -> axis = None
    # sort and conver 1-d array

Original Array: 
 [[17  8  8 11 12]
 [17 16 17  6  9]
 [15  5  6 18 10]
 [10 13 13 18 19]]
Original Array: 
 [[ 8  8 11 12 17]
 [ 6  9 16 17 17]
 [ 5  6 10 15 18]
 [10 13 13 18 19]]


### 3. Sorting Indices

-  np.argsort(arr)

- return the sorted indeces of the given array

In [39]:
# 1-d:  np.argsort()

arr1 = np.random.randint(2,10, size = (8,))

print("Original Array: \n", arr1)

# apply np.argsort(arr)

idxs = np.argsort(arr1)

# idx of sorted elements
print("The Index position of sorted Elements: ", idxs)


# vals = idxs[]

print("The sorted elements: ", vals)


Original Array: 
 [4 6 7 6 3 2 8 6]
The Index position of sorted Elements:  [5 4 0 1 7 3 2 6]
The sorted elements:  [2 4 5 8 8 8 8 9]


In [ ]:
# 2-d: np.argsort(arr)

# arr2 = np.random.randint(5,20, size = (4,5))

# print("Original Array: \n", arr2)

# # apply np.argsort(arr) 

# idxs = np.argsort(arr2)

# print("The sorted Element index position in main array: \n", idxs)


# # find the Elements

# print("Shape arr1: ", arr2.shape)  # (4,5)

# print("Sorted Elements : \n", idxs[4,5])




Original Array: 
 [[ 9 10 17  5  9]
 [ 5  5  9  8  6]
 [14 17 14 13 15]
 [ 9  5 15 11 17]]
The sorted Element index position in main array: 
 [[3 0 4 1 2]
 [0 1 4 3 2]
 [3 0 2 4 1]
 [1 0 3 2 4]]
Shape arr1:  (4, 5)


IndexError: index 4 is out of bounds for axis 0 with size 4

### 4. Decending sort

### 5. Practices with Real-life Examples