## Topic: Searching ndarray

### OUTCOMES

- 1. Definition

- 2. np.where()

- 3. np.nonzero()

- 4. np.argmax()

- 5. np.argmin()



### 1. Definition

- Searching in numpy means finding the indices or positions of elements in an array that satisfy a given condition (like greater then , equal to etc.)

### 2. np.where()

- basic syntax:
    - np.where(condition)

    - returns indices where condition is True.

- another syntax:

    - np.where(condition, x,y)

        - x = True_value if cds is true.
        - y = False value if the condition it false

In [1]:
import numpy as np

In [ ]:
# np.where(condition) 

# 1-d:

arr1 = np.random.randint(4,20, size = (8,))

print("Arr1: \n", arr1)

# return index
idxs = np.where(arr1 > 10)  # greater then 10 only true indices are return

print("Greater than 10 all indices: ", idxs)

# access values
print("Greater than 10 all elements: ", arr1[idxs])


Arr1: 
 [14 16 17 13  7 19  5  8]
Greater than 10 all indices:  (array([0, 1, 2, 3, 5]),)
Greater than 10 all elements:  [14 16 17 13 19]


In [ ]:
# np.where(condition)
# 1-d:

arr1 = np.arange(1,13)

print(arr1)

less_than_5_idx = np.where(arr1 < 5)

not_equal_10_idx = np.where(arr1 != 10)

greater_than_equal_8_idx = np.where(arr1 >=8)



print("Less than 5 elements idxs: ", less_than_5_idx)

print("Not equal 10 element idxs: ", not_equal_10_idx)

print("Greater than or equal 8 element idxs: ", greater_than_equal_8_idx)

# NOTE-> Return indices of the elments

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Less than 5 elements idxs:  (array([0, 1, 2, 3]),)
Not equal 10 element idxs:  (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11]),)
Greater than or equal 8 element idxs:  (array([ 7,  8,  9, 10, 11]),)


- Second form:

    - np.where(condition, x,y)

        - x = True_value if cds is true.
        - y = False value if the condition it false

In [ ]:
# 1-d: Replace zero values with 100

arr1 = np.random.randint(0,2, size=(10,))

print("Original Array: \n", arr1)


remove_zero_arr = np.where(arr1 <= 0, 100, arr1)

print("Replace zero vlaues to 100: \n", remove_zero_arr)



Original Array: 
 [0 0 1 1 1 0 0 0 0 0]
Replace zero vlaues to 100: 
 [100 100   1   1   1 100 100 100 100 100]


In [40]:
# for categorize value : np.where()

marks_arr = np.random.randint(40,90, size = (20,))

print("Original array: \n", marks_arr)

# if marks_arr values is less then 50 "Fail", else "Pass"

grades = np.where(marks_arr < 50, "Fail", "Pass")

print(grades)



Original array: 
 [54 57 64 42 41 49 69 78 76 48 50 45 81 48 48 78 75 54 74 62]
['Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Fail'
 'Pass' 'Fail' 'Pass' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [ ]:
# np.where(condition) for 2-d:

# - return indices(row, col) of all elements where given condition is True.

arr2 = np.array([
    [10, 11, 4, 6],
    [9, 21, 98,65],
    [21, 2, 1, 5]
    ])

# find indices
idxs = np.where(arr2 > 10)
print(idxs)

# find the idx values

vals = arr2[idxs]
print(vals)

(array([0, 1, 1, 1, 2]), array([1, 1, 2, 3, 0]))


In [ ]:
'''  
what is the meaning this output?
(array([0, 1, 1, 1, 2]), array([1, 1, 2, 3, 0]))

- [0, 1, 1, 1, 2] represent x-axis(rows) indices

- [1, 1, 2, 3, 0] represent y-axis(column) idxs

so [row,col]

 - [0,1] => position element that greater than 10
 - [1,1] => element is greater than 10
 - [1,2] => elment is greater than 10
 - [1,3] => element is greater than 10
 - [2,0] => element is greater than 10



'''

In [ ]:
# 2-d : where(condition, x, y)
#       x = True values
#       y = False values


images = np.random.randint(20,255, size = (4,6))

print("Original Images: \n", images)

theshold = 100


binary_mask = np.where(images > theshold, 1, 0)

print("Binary Mask: \n", binary_mask)

# replace : 100 > images with 1
#  less then 100 with 0

Original Images: 
 [[143  70  22 205 217 242]
 [200 216 253 105 113 159]
 [130 202  71 241 148  63]
 [166 151 214  23 192  85]]
Binary Mask: 
 [[1 0 0 1 1 1]
 [1 1 1 1 1 1]
 [1 1 0 1 1 0]
 [1 1 1 0 1 0]]


### 3. np.nonzero()

- Returns the indices of all elements that are non-zero.

In [ ]:
# 2-d array:

arr = np.random.randint(0,2, size = (4,3))

print("Arr: \n", arr)

idx_zero = np.nonzero(arr)

print("All Zero Element idx: ", idx_zero)


print("All Row idx   : ", arr[0])
print("All Column idx: ", arr[1])

print("Find zero: ", arr[0][1]) # 0 present row 0 and coluns 1



Arr: 
 [[1 0 1]
 [0 1 1]
 [0 1 1]
 [0 0 1]]
All Zero Element idx:  (array([0, 0, 1, 1, 2, 2, 3]), array([0, 2, 1, 2, 1, 2, 2]))
All Row idx   :  [1 0 1]
All Column idx:  [0 1 1]
Find zero:  0


### 4. np.argmax()

- return the max values index of first occurence

In [53]:
arr = np.array(
    [10, 30, 90, 50, 66, 90, 45]
)

print("Max idx: ", np.argmax(arr))

Max idx:  2


### 5. np.argmin()

- return the minimun elements idx

In [55]:
arr = np.array(
    [60, 70, 90, 50, 6, 90, 45]
)

min_idx = np.argmin(arr)

print("Minmul Element idx: ", min_idx)

Minmul Element idx:  4
