## Topic: Counting & Unique Elements in NumPy


### OUTCOMES

- 1. np.count_nonzero()

- 2. np.unique()


In [1]:
import numpy as np

### 1. np.count_nonzero(arr)

- count how many elements in the array are non-zero.
- ignores zeros and False values -> 0

In [ ]:
# 1-d : counting 

arr1 = np.array([1, 2, 4, 5, 0, 6, 4, 3,0])

count = np.count_nonzero(arr1)

print("Total nonZero: ", count)


Total nonZero:  7


In [7]:
# conditional counting

arr = np.random.randint(1,15, size= (50,))


print("Arr: \n", arr)

count = np.count_nonzero(arr > 20)

print("Total Element greater than 20: ", count)

count1 = np.count_nonzero(arr < 10)
print("Total Element less than 10: ", count1)

Arr: 
 [10 10 12 10  6  1  4  6 12 12  8  9 14 13  9  7  5 10  3  9  3  7 11 13
  5  2 10 10 13  7 14  2  1 11 14  8  4  9 12  5 13  5  1 10  8  4 11  5
  3  6]
Total Element greater than 20:  0
Total Element less than 10:  29


In [ ]:
# for 2-d array: counting
arr = np.random.randint(10,50, size= (3,4))

print("Arr: \n", arr)

total_non_zero = np.count_nonzero(arr)

print("Total non zero Element: ", total_non_zero)

less_than_30 = np.count_nonzero(arr < 30)

print("Less then 30: ", less_than_30)



Arr: 
 [[40 42 10 42]
 [37 24 37 27]
 [26 49 26 12]]
Total non zero Element:  12
Less then 30:  6


In [ ]:
# 2-d array:

arr2 = np.array([
    [12, 0, 3, 6],
    [21, 44, 9, 0],
    [5, 22, 5, 33],
    [7, 5, 3, 3]
])

total_no_zero = np.count_nonzero(arr2)

total_no_zero_row = np.count_nonzero(arr2, axis = 1)
total_no_zero_col = np.count_nonzero(arr2, axis = 0)



print("Total non zero element in arr : ", total_no_zero)
print("Total non zero per elements rows: ", total_no_zero_row)
print("Total non zero elements per cols : ", total_no_zero_col)



Total non zero element in arr :  14
Total non zero element in rows:  [3 3 4 4]
Total non zero element in col :  [4 3 4 3]


In [19]:
greater_than_10 = np.count_nonzero(arr2 > 10, axis = 1)

print("Per rows greater than 10 elemnt ", greater_than_10)

Per rows greater than 10 elemnt  [1 2 2 0]


### 2. np.unique()


- Find all unique elements in an array and can also return counts, indices 

In [20]:
# Example : np.unique()

arr = np.array([10, 20, 40, 30, 10, 20])

unique_vals = np.unique(arr)

print("Unique Value: ", unique_vals)


Unique Value:  [10 20 30 40]


In [ ]:
# np.unique() with counts
# np.unique(arr, return_counts = True)
#    - return two values:
#            first unique values and second counts of unique values

arr = np.array([10, 20, 30, 40, 50, 60, 70, 10, 20])


vals,count = np.unique(arr,return_counts = True)

print("Unique values: ", vals)
print("Total of uniques values: ", count)

# here, 
#  10 is present -> 2
# 20 is present -> 2
# rest of values are -> 1

Unique values:  [10 20 30 40 50 60 70]
Total uniques values:  [2 2 1 1 1 1 1]
