### Practices_Problem in Nummpy

In [1]:
import numpy as np

### Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [16]:
# Solve - 1:

arr = np.random.randint(1,21, size=(5,5))

print("Array: \n", arr)

# Replace all the element in the third column with 1

# access and replace

arr[: , [2]] = 1    # or -> arr[0:, 2] = 1
# arr[0:, 2:3] = 1

print("After Replace: \n", arr)



Array: 
 [[14  9  5  7 19]
 [13 15 12  5 20]
 [14 18 10  8  5]
 [ 7  2 11 15 17]
 [11  8 13  6 12]]
After Replace: 
 [[14  9  1  7 19]
 [13 15  1  5 20]
 [14 18  1  8  5]
 [ 7  2  1 15 17]
 [11  8  1  6 12]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [21]:
arr = np.random.randint(1,17, size = (4,4))

print("Array: \n", arr)

# Replace diagonal elements
np.fill_diagonal(arr,0)


print("After Replace diagonal element: \n", arr)

Array: 
 [[16  2 10  2]
 [ 8  6  3 11]
 [ 9  8  4  5]
 [ 5 10 10 16]]
After Replace diagonal element: 
 [[ 0  2 10  2]
 [ 8  0  3 11]
 [ 9  8  0  5]
 [ 5 10 10  0]]


### Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [ ]:
arr = np.random.randint(1,37, size = (6,6))

print("Arrray: \n", arr)

sub_arr = arr[2:5 , 1:4]

print("Sub Array: \n", sub_arr)


Arrray: 
 [[35 15 12 35  1 21]
 [20  6 28 19 32 10]
 [32 22 16  4 30 28]
 [11 36 25 23  4  8]
 [25 34 11 25 36 24]
 [13 32 28 16 31  8]]
Sub Array: 
 [[22 16  4]
 [36 25 23]
 [34 11 25]]



2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
arr = np.random.randint(1, 20, size=(5,5))

print("Array: \n",arr)
print()

# Extract elements on the border
borders_row1 = arr[0,0:]
borders_row2 = arr[-1,0:]

border_in_col1 = arr[1:-1 , 0]
border_in_col2 = arr[1:-1 , 4]

print("\nFirst Row border", borders_row1)

print("\nLast Row border : ", borders_row2)

print("\nFirst Col border: ", border_in_col1)

print("\nLast Col border", border_in_col2)

# print(np.concatenate((borders_row1, borders_row2, border_in_col1,border_in_col2)))

print(np.concatenate((borders_row1, border_in_col1,borders_row2, border_in_col2)))

corner_border_elements = arr[0:6:4, 0:5:4]
print("Corner border Elements: \n", border_elements)


Array: 
 [[17  4 16  1  7]
 [ 8 17  5  7 13]
 [17  8  8  2 10]
 [17 12 16  1 13]
 [14  1  8  2 12]]


First Row border [17  4 16  1  7]

Last Row border :  [14  1  8  2 12]

First Col border:  [ 8 17 17]

Last Col border [13 10 13]
[17  4 16  1  7  8 17 17 14  1  8  2 12 13 10 13]
Corner border Elements: 
 [[11 19]
 [14  2]]


### Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1 = np.random.randint(1,10, size = (3,4))
arr2 = np.random.randint(10,20, size = (3,4))

print("Array1: \n", arr1)
print("Array2: \n", arr2)

# element wise Perfom
## Addition
add = arr1 + arr2
print("Addition: \n", add)

## subtraction
sub = arr1 - arr2
print("subtraction: \n", sub)

## Multiplication
mul = arr1 * arr2
print("Multiplication: \n", mul)


## division
div = arr1 / arr2
print("division: \n", div)


Array1: 
 [[4 5 7 5]
 [4 8 7 2]
 [1 2 5 1]]
Array2: 
 [[19 11 11 17]
 [10 10 18 17]
 [15 17 16 15]]
Addition: 
 [[23 16 18 22]
 [14 18 25 19]
 [16 19 21 16]]
subtraction: 
 [[-15  -6  -4 -12]
 [ -6  -2 -11 -15]
 [-14 -15 -11 -14]]
Multiplication: 
 [[ 76  55  77  85]
 [ 40  80 126  34]
 [ 15  34  80  15]]
division: 
 [[0.21052632 0.45454545 0.63636364 0.29411765]
 [0.4        0.8        0.38888889 0.11764706]
 [0.06666667 0.11764706 0.3125     0.06666667]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [74]:
arr = np.arange(1,17).reshape(4,4)

print("Array: \n", arr)

# row-wise sum

row_sum = np.sum(arr, axis = 1)

print("Rows wise sum: ", row_sum)


# column wise sum

coln_sum = np.sum(arr, axis = 0)

print("Column Wise sum: ", coln_sum)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Rows wise sum:  [10 26 42 58]
Column Wise sum:  [28 32 36 40]


### Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [78]:
arr = np.random.randint(1,25, size = (5,5))

print("Array: \n", arr)

# mean
mean_arr = np.mean(arr)
print("Mean: ", mean_arr)

# median
median_arr = np.median(arr)
print("Median: ", mean_arr)

# standard deviation
std_arr = np.std(arr)
print(f"Standard Deviation: {std_arr:.2f}")

# variance
var_arr = np.var(arr)
print(f"Variance: {var_arr:.3f}") 

Array: 
 [[13  9 15 20 22]
 [18 23  6  4  2]
 [24 20 10 14  8]
 [ 5 12 17 24 16]
 [24 17 11  6  8]]
Mean:  13.92
Median:  13.92
Standard Deviation: 6.74
Variance: 45.434


### Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [98]:
arr_2 = np.random.randint(5,50, size = (3,3))

print("\nArray (2-d): \n", arr_2)

# 1-d array
arr_1 = np.random.randint(1,20, size = (3,))
print("\nArray (1-d): \n", arr_1)


# addition 
print("\nAddition of each row-wise: \n", arr_2 + arr_1)
# print("\nAddition: \n", arr_1 + arr_2)




Array (2-d): 
 [[17 25 13]
 [40 14 44]
 [44 22 31]]

Array (1-d): 
 [ 7  1 19]

Addition of each row-wise: 
 [[24 26 32]
 [47 15 63]
 [51 23 50]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [97]:
arr2 = np.random.randint(2,20, size = (4,4))

print("\nArray 2d: \n", arr2)


# 1-d array
arr_1 = np.random.randint(1,20, size = (4,))

# reshape
arr21 = arr_1.reshape(4,1)

print("Arr21: \n", arr21)

# Substraction 
print("\nSubtract of Each Column-wise: \n", arr2 - arr21)




Array 2d: 
 [[18 13 19 13]
 [ 5  4 17 11]
 [11 11 18 14]
 [14 19 18  4]]
Arr21: 
 [[17]
 [10]
 [18]
 [10]]

Subtract of Each Column-wise: 
 [[ 1 -4  2 -4]
 [-5 -6  7  1]
 [-7 -7  0 -4]
 [ 4  9  8 -6]]


### Linear Algebra

1. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [99]:
arr1 = np.array(
    [[2, 4, 6],
    [1, 3, 5]]
    )
arr2 = np.array(
    [[4, 2],
    [6, 8],
    [3, 5]]
    )

# Matrix Multiplication

matrix_mul = np.dot(arr1, arr2)


print("Matrix Multiplication: \n", matrix_mul)


Matrix Multiplication: 
 [[50 66]
 [37 51]]


### Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [103]:
arr1 = np.arange(1,10).reshape(3,3)

print("Array: \n", arr1)

arr2 = arr1.reshape(1,9)

print("Array2: \n", arr2)

arr3 = arr2.reshape(9,1)

print("Array3: \n", arr3)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array2: 
 [[1 2 3 4 5 6 7 8 9]]
Array3: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]



2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [ ]:
arr1 = np.random.randint(5,20, size = (5,5))

print("Array1: \n", arr1)

# Flattern
arr2 = arr1.flatten()

print("Array Flattern: \n", arr2)

# again Reshape
arr3 = arr2.reshape(5,5)

print("Array3: \n", arr3)


Array1: 
 [[17 14  8 14 19]
 [ 6 18  5 15 10]
 [17  6  9 19  6]
 [13  9 11 16 14]
 [13 11  8 12 15]]
Array Flattern: 
 [17 14  8 14 19  6 18  5 15 10 17  6  9 19  6 13  9 11 16 14 13 11  8 12
 15]
Array3: 
 [[17 14  8 14 19]
 [ 6 18  5 15 10]
 [17  6  9 19  6]
 [13  9 11 16 14]
 [13 11  8 12 15]]


### **Boolean Indexing**

1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [115]:
arr = np.random.randint(1, 50, size = (4,4))

print("Array: \n", arr)


# use boolean indexing

arr[arr > 10] = 10

print("Array's element Greater than 10: \n", arr)



Array: 
 [[ 7 43 25  3]
 [41  4 33 45]
 [43 23 36  8]
 [23 14  7 27]]
Array's element Greater than 10: 
 [[ 7 10 10  3]
 [10  4 10 10]
 [10 10 10  8]
 [10 10  7 10]]
