### Topic: Online judge

Proble_01: Easy: Reshape Matrix
https://www.deep-ml.com/problems/3

- input: 
    a = [[1,2,3,4],[5,6,7,8]], new_shape = (4, 2)

- output:
    [[1, 2], [3, 4], [5, 6], [7, 8]]

In [ ]:
import numpy as np

- Q.n: 
Write a Python function that reshapes a given matrix into a specified shape. if it cant be reshaped return back an empty list [ ]

In [17]:
# Solution:

def reshape_matrix(a, new_shape):
    arr = np.array(a)

    arr1 = arr.reshape(new_shape)

    size_arr = arr.size

    size_arr1 = arr1.size

    # print("arr1: ", size_arr)
    # print("arr2: ", size_arr1)

    if size_arr == size_arr1:
        return arr1.tolist()
    else:
        return []


a = [[1,2,3,4],
    [5,6,7,8]]

# print(a, type(a))
new_shape = (4, 2)

new_reshape_matrix = reshape_matrix(a, new_shape)
print(new_reshape_matrix)




[[1, 2], [3, 4], [5, 6], [7, 8]]


In [ ]:
    size_arr = arr.size

    arr2 = np.array(new_shape)
    size_shape = arr2.size

    print(size_arr, size_shape)

Problem_02: Easy
https://www.deep-ml.com/problems/5

In [ ]:


- Input:
matrix = [[1, 2], [3, 4]], scalar = 2


- Output:
    [[2, 4], [6, 8]]


#### Scalar Multiplication of a Matrix

- Write a Python function that multiplies a matrix by a scalar and returns the result.

In [19]:
# Solution_02

def scalar_multiply(matrix, scalar):
    arr = np.array(matrix)
	
    # multiplication
    result = np.dot(arr, scalar)  
    
    return result.tolist()


matrix = [[1, 2], 
          [3, 4]]

scalar = 2

ans = scalar_multiply(matrix, scalar)

print(ans)


[[2, 4], [6, 8]]


Problem -03: Easy
https://www.deep-ml.com/problems/35



- Input:
x = np.array([1, 2, 3])
    output = make_diagonal(x)
    print(output)
Output:
    [[1. 0. 0.]
        [0. 2. 0.]
        [0. 0. 3.]]

#### Convert Vector to Diagonal Matrix

- Write a Python function to convert a 1D numpy array into a diagonal matrix. The function should take in a 1D numpy array x and return a 2D numpy array representing the diagonal matrix.

In [ ]:
import numpy as np

def make_diagonal(x):
	output = np.diag(x)

	return output
	
	
x = np.array([1, 2, 3])

make_diagonal(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Problem - 04: Easy
https://www.deep-ml.com/problems/83



- Input:
    vec1 = np.array([1, 2, 3]), vec2 = np.array([4, 5, 6])

- Output:
    32

#### Dot Product Calculator

Write a Python function to calculate the dot product of two vectors. The function should take two 1D NumPy arrays as input and return the dot product as a single number.




In [21]:
def calculate_dot_product(vec1, vec2):
    product = np.dot(vec1, vec2)

    return product



vec1 = np.array([1, 2, 3])

vec2 = np.array([4, 5, 6])

result = calculate_dot_product(vec1, vec2)

print(result)

32


Easy
https://www.deep-ml.com/problems/121



- Input:
    a = [1, 3], b = [4, 5]
- Output:
    [5, 8]

#### Vector Element-wise Sum

Write a Python function that computes the element-wise sum of two vectors. The function should return a new vector representing the resulting sum if the operation is valid, or -1 if the vectors have incompatible dimensions. Two vectors (lists) can be summed element-wise only if they are of the same length.


In [29]:
def vector_sum(a, b):
    len_a = len(a)
    len_b = len(b)
    
    arr_a = np.array(a)
    arr_b = np.array(b)

    if len_a != len_b:
        return -1
    else:
        return (arr_a + arr_b).tolist()
    
a = [1, 3]
b = [4, 5]

ans = vector_sum(a,b)

print(ans)

[5, 8]


In [ ]:
What will be the output?

nums = [2,4,6,8,10]

nums[2] = nums[2] * nums[0]

print(nums)

