## Topic: 5. DataFrame From In-build Data Structure (list, tuple, dic)

### OUTCOMES

- 1. Transforming to df form list.

- 2. Transforming to df from tuple

- 3. Transforming to df from dic

- 4. Transforming to df from list of list

In [2]:
import pandas as pd

- Basic syntax for Transforming:
    - df = pd.DataFram(sequence)
    - eg:
        - df = pd.DataFram(list)

### 1. Transforming to df form list

In [ ]:
# Example: df from Nested list

lst = [
    [10, 20, 30], 
    [40, 50, 60], 
    [70, 80, 90],
    [21, 32, 42]
]

print("Type: ", type(lst))  # list

# convert to DataFrame

df = pd.DataFrame(lst)

print("Type : ", type(df))

df

# NOTE -> indices are automatically generated

Type:  <class 'list'>
Type :  <class 'pandas.core.frame.DataFrame'>


0   1   2
0  10  20  30
1  40  50  60
2  70  80  90
3  21  32  42

- Rename the column name

- synatax: pd.DataFrame(sequenc, columns = ['c1', 'c2' , 'c3'])

In [7]:
# Rename the column

df = pd.DataFrame(lst,columns = ["Math_Mark", "English Mark", "DSA Mark"])
df

Math_Mark  English Mark  DSA Mark
0         10            20        30
1         40            50        60
2         70            80        90
3         21            32        42

Question?

In [ ]:
# Example: 2-d to df

import numpy as np

# create 2-d
arr2 = np.random.randint(10, 40, size = (4,3))

print("Type: ", type(arr2))
print(arr2)

# convert into df and Rename the column and rows idx 

df = pd.DataFrame(arr2, columns = ["Sub1", "Sub2", "Sub3"], index = [1,2,3,4])

print("Type: ", type(df))

# Rename the idx of rows
# df = pd.DataFrame(df, index = [1,2,3,4])

df

Type:  <class 'numpy.ndarray'>
[[38 32 31]
 [34 11 16]
 [28 12 10]
 [33 14 24]]
Type:  <class 'pandas.core.frame.DataFrame'>


Sub1  Sub2  Sub3
1    38    32    31
2    34    11    16
3    28    12    10
4    33    14    24

### 2. Transforming to df form tuple

In [ ]:
# df from tuple (Nested)

tpl = (("name", "Kz"), ("age", 23), ("mark", 55))

print("Tuple: ", tpl)
print("Type: ", type(tpl))

# convert to df and rename the columns and rows

df = pd.DataFrame(tpl, columns = ["Name", "Propertices"], index = [8,4,6])


df


Tuple:  (('name', 'Kz'), ('age', 23), ('mark', 55))
Type:  <class 'tuple'>


Name Propertices
8  name          Kz
4   age          23
6  mark          55

### 3. Transforming to df form dict

In [ ]:
# Example: df from dic 

my_dict = {
    "Name": ["Kz", "Ra", "KzRaihan"],
    "age" : [24,35, 30]
}

print("Type: ", type(my_dict))


# convert to df

df = pd.DataFrame(my_dict)

df

# NOTE -> Dictionaries all keys are convert to columns name automatically.


Type:  <class 'dict'>


Name  age
0        Kz   24
1        Ra   35
2  KzRaihan   30

### 4. Transforming to df form list of dic

In [ ]:
# list of dictionary to df

lst_dict = [

    {
        "Name": "Kz", 
        "age" : 25,
        "City": "New York"
    },
    {
        "Name": "Ra",
        "age": 24,
        "City": "Paris",
        # "Home": "ABC"

    },

    {
        "Name": "KzRaihan", 
        "age" : 21,
    # here city is missing

    }
 

]

print("Type: ", type(lst_dict))


df = pd.DataFrame(lst_dict)
df


# Missing Value with Replace with NaN

Type:  <class 'list'>


Name  age      City
0        Kz   25  New York
1        Ra   24     Paris
2  KzRaihan   21       NaN